-- Legal Filing Requirements Seed - All 50 States (Divorce)
-- Run this after 002_data_ingestion_schema.sql

-- =====================================================
-- DIVORCE FILING REQUIREMENTS BY STATE
-- =====================================================

INSERT INTO lf_filing_requirements (
  state_code, county, filing_type, filing_fee, fee_waiver_available,
  residency_requirement, waiting_period_days, mandatory_mediation,
  mandatory_parenting_class, required_forms, service_requirements,
  efiling_available, efiling_system, special_rules, source_url, last_verified
) VALUES
('AL', NULL, 'divorce', 350, true, '6 months state residency', 30, false, true, ARRAY['CS-47 Petition for Divorce'], '{"methods": ["personal", "certified_mail"], "days_to_respond": 30}', true, 'Alafile', '{"grounds": "no_fault_or_fault", "legal_separation_available": true}', 'https://judicial.alabama.gov/', CURRENT_DATE),
('AK', NULL, 'divorce', 250, true, 'State resident at time of filing', 0, false, true, ARRAY['DR-100 Complaint for Divorce'], '{"methods": ["personal", "certified_mail"], "days_to_respond": 20}', true, 'TrueFiling', '{"grounds": "incompatibility", "legal_separation_available": true}', 'https://courts.alaska.gov/', CURRENT_DATE),
('AZ', NULL, 'divorce', 349, true, '90 days state residency', 60, true, true, ARRAY['Petition for Dissolution'], '{"methods": ["personal", "certified_mail", "acceptance"], "days_to_respond": 20}', true, 'AZTurboCourt', '{"grounds": "irretrievably_broken", "covenant_marriage_rules": true}', 'https://www.azcourts.gov/', CURRENT_DATE),
('AR', NULL, 'divorce', 165, true, '60 days state residency (90 for plaintiff)', 30, false, false, ARRAY['DV-1 Complaint for Divorce'], '{"methods": ["personal", "certified_mail"], "days_to_respond": 30}', true, 'eFlex', '{"grounds": "18_months_separation", "fault_grounds_available": true}', 'https://www.arcourts.gov/', CURRENT_DATE),
('CA', NULL, 'divorce', 435, true, '6 months state, 3 months county', 180, true, true, ARRAY['FL-100 Petition', 'FL-110 Summons'], '{"methods": ["personal", "substituted", "certified_mail"], "days_to_respond": 30}', true, 'Various by county', '{"grounds": "irreconcilable_differences", "domestic_partnership_dissolution": true}', 'https://www.courts.ca.gov/', CURRENT_DATE),
('CO', NULL, 'divorce', 230, true, '91 days state residency', 91, true, true, ARRAY['JDF 1102 Petition', 'JDF 1103 Summons'], '{"methods": ["personal", "certified_mail"], "days_to_respond": 21}', true, 'Colorado Courts E-Filing', '{"grounds": "irretrievably_broken", "decree_can_be_granted_91_days": true}', 'https://www.courts.state.co.us/', CURRENT_DATE),
('CT', NULL, 'divorce', 350, true, '12 months state residency', 90, true, true, ARRAY['JD-FM-3 Complaint', 'JD-FM-3A Summons'], '{"methods": ["personal"], "days_to_respond": 30}', true, 'CT e-Services', '{"grounds": "irretrievable_breakdown", "90_day_waiting_from_return_date": true}', 'https://jud.ct.gov/', CURRENT_DATE),
('DE', NULL, 'divorce', 150, true, '6 months state residency', 0, true, true, ARRAY['Petition for Divorce'], '{"methods": ["personal", "certified_mail"], "days_to_respond": 20}', true, 'File & ServeXpress', '{"grounds": "incompatibility", "reconciliation_provision": true}', 'https://courts.delaware.gov/', CURRENT_DATE),
('FL', NULL, 'divorce', 408, true, '6 months state residency', 20, true, true, ARRAY['Family Law Form 12.901(a)', 'Summons'], '{"methods": ["personal", "certified_mail"], "days_to_respond": 20}', true, 'Florida Courts E-Filing Portal', '{"grounds": "irretrievably_broken", "simplified_dissolution_available": true}', 'https://www.flcourts.org/', CURRENT_DATE),
('GA', NULL, 'divorce', 230, true, '6 months state residency', 30, false, true, ARRAY['Petition for Divorce'], '{"methods": ["personal", "certified_mail"], "days_to_respond": 30}', true, 'PeachCourt', '{"grounds": "irretrievably_broken", "12_fault_grounds_available": true}', 'https://www.georgiacourts.gov/', CURRENT_DATE),
('HI', NULL, 'divorce', 250, true, '6 months state residency', 0, false, true, ARRAY['Complaint for Divorce'], '{"methods": ["personal", "certified_mail"], "days_to_respond": 20}', true, 'JEFS', '{"grounds": "irretrievable_breakdown", "marriage_breakdown_2_years": true}', 'https://www.courts.state.hi.us/', CURRENT_DATE),
('ID', NULL, 'divorce', 207, true, '6 weeks state residency', 20, false, true, ARRAY['CAO FLDv 1-3 Petition'], '{"methods": ["personal", "certified_mail"], "days_to_respond": 21}', true, 'iCourt', '{"grounds": "irreconcilable_differences", "fault_grounds_available": true}', 'https://isc.idaho.gov/', CURRENT_DATE),
('IL', NULL, 'divorce', 337, true, '90 days state residency', 0, true, true, ARRAY['Petition for Dissolution'], '{"methods": ["personal", "certified_mail", "special_process_server"], "days_to_respond": 30}', true, 'Odyssey eFileIL', '{"grounds": "irreconcilable_differences", "6_month_separation_presumption": true}', 'https://www.illinoiscourts.gov/', CURRENT_DATE),
('IN', NULL, 'divorce', 157, true, '6 months state, 3 months county', 60, false, true, ARRAY['Petition for Dissolution'], '{"methods": ["personal", "certified_mail"], "days_to_respond": 20}', true, 'Odyssey', '{"grounds": "irretrievable_breakdown", "final_hearing_after_60_days": true}', 'https://www.in.gov/courts/', CURRENT_DATE),
('IA', NULL, 'divorce', 185, true, '1 year state residency', 90, true, true, ARRAY['Petition for Dissolution'], '{"methods": ["personal", "certified_mail"], "days_to_respond": 20}', true, 'EDMS', '{"grounds": "marriage_breakdown", "90_day_waiting_period": true}', 'https://www.iowacourts.gov/', CURRENT_DATE),
('KS', NULL, 'divorce', 195, true, '60 days state residency', 60, true, true, ARRAY['Petition for Divorce'], '{"methods": ["personal", "certified_mail"], "days_to_respond": 20}', true, 'Kansas eCourt', '{"grounds": "incompatibility", "60_day_waiting_period": true}', 'https://www.kscourts.org/', CURRENT_DATE),
('KY', NULL, 'divorce', 148, true, '180 days state residency', 60, true, true, ARRAY['AOC-238 Petition'], '{"methods": ["personal", "certified_mail"], "days_to_respond": 20}', true, 'eFiling Kentucky', '{"grounds": "irretrievable_breakdown", "60_day_separation_or_court_finds": true}', 'https://courts.ky.gov/', CURRENT_DATE),
('LA', NULL, 'divorce', 400, true, 'State domicile', 180, false, true, ARRAY['Petition for Divorce'], '{"methods": ["personal", "certified_mail"], "days_to_respond": 15}', true, 'Various by parish', '{"grounds": "living_separate_180_days", "covenant_marriage_rules": true}', 'https://www.lasc.org/', CURRENT_DATE),
('ME', NULL, 'divorce', 120, true, '6 months state residency', 60, true, true, ARRAY['FM-001 Complaint'], '{"methods": ["personal", "certified_mail"], "days_to_respond": 20}', true, 'Odyssey', '{"grounds": "irreconcilable_differences", "mediation_required_for_custody": true}', 'https://www.courts.maine.gov/', CURRENT_DATE),
('MD', NULL, 'divorce', 165, true, '6 months or 12 months for certain grounds', 0, true, true, ARRAY['CC-DR-20 Complaint'], '{"methods": ["personal", "certified_mail"], "days_to_respond": 30}', true, 'MDEC', '{"grounds": "mutual_consent_or_12_month_separation", "limited_divorce_available": true}', 'https://www.mdcourts.gov/', CURRENT_DATE),
('MA', NULL, 'divorce', 215, true, '1 year state or grounds occurred in state', 120, false, true, ARRAY['CJ-D 101 Complaint'], '{"methods": ["personal", "certified_mail"], "days_to_respond": 20}', true, 'Massachusetts Trial Court E-Filing', '{"grounds": "irretrievable_breakdown", "1A_or_1B_process": true}', 'https://www.mass.gov/orgs/trial-court', CURRENT_DATE),
('MI', NULL, 'divorce', 175, true, '180 days state, 10 days county', 60, true, true, ARRAY['FOC 102 Complaint'], '{"methods": ["personal", "certified_mail"], "days_to_respond": 21}', true, 'MiFILE', '{"grounds": "breakdown_of_marriage", "180_days_if_children": true}', 'https://courts.michigan.gov/', CURRENT_DATE),
('MN', NULL, 'divorce', 365, true, '180 days state residency', 0, true, true, ARRAY['Summons', 'Petition'], '{"methods": ["personal", "certified_mail"], "days_to_respond": 30}', true, 'eFS', '{"grounds": "irretrievable_breakdown", "summary_dissolution_available": true}', 'https://www.mncourts.gov/', CURRENT_DATE),
('MS', NULL, 'divorce', 52, true, '6 months state residency', 60, false, false, ARRAY['Complaint for Divorce'], '{"methods": ["personal", "certified_mail"], "days_to_respond": 30}', true, 'MEC', '{"grounds": "irreconcilable_differences", "requires_property_agreement": true}', 'https://courts.ms.gov/', CURRENT_DATE),
('MO', NULL, 'divorce', 163, true, '90 days state residency', 30, false, true, ARRAY['Petition for Dissolution'], '{"methods": ["personal", "certified_mail"], "days_to_respond": 30}', true, 'CaseNet', '{"grounds": "irretrievably_broken", "30_day_minimum": true}', 'https://www.courts.mo.gov/', CURRENT_DATE),
('MT', NULL, 'divorce', 170, true, '90 days state residency', 20, true, true, ARRAY['Petition for Dissolution'], '{"methods": ["personal", "certified_mail"], "days_to_respond": 20}', true, 'File & ServeXpress', '{"grounds": "irretrievable_breakdown", "parenting_education_required": true}', 'https://courts.mt.gov/', CURRENT_DATE),
('NE', NULL, 'divorce', 158, true, '1 year state or married in NE', 60, true, true, ARRAY['Complaint for Dissolution'], '{"methods": ["personal", "certified_mail"], "days_to_respond": 30}', true, 'Nebraska Judicial Branch E-Filing', '{"grounds": "irretrievably_broken", "60_day_waiting_period": true}', 'https://supremecourt.nebraska.gov/', CURRENT_DATE),
('NV', NULL, 'divorce', 299, true, '6 weeks state residency', 0, false, true, ARRAY['Complaint for Divorce'], '{"methods": ["personal", "certified_mail"], "days_to_respond": 20}', true, 'Various by county', '{"grounds": "incompatibility", "quickie_divorce_available": true}', 'https://nvcourts.gov/', CURRENT_DATE),
('NH', NULL, 'divorce', 252, true, '1 year state residency', 0, true, true, ARRAY['Petition for Divorce'], '{"methods": ["personal", "certified_mail"], "days_to_respond": 30}', true, 'NH eCourt', '{"grounds": "irreconcilable_differences", "mandatory_mediation": true}', 'https://www.courts.state.nh.us/', CURRENT_DATE),
('NJ', NULL, 'divorce', 300, true, '12 months state residency', 0, true, true, ARRAY['Complaint for Divorce'], '{"methods": ["personal", "certified_mail"], "days_to_respond": 35}', true, 'eCourts', '{"grounds": "irreconcilable_differences_6_months", "fault_grounds_available": true}', 'https://www.njcourts.gov/', CURRENT_DATE),
('NM', NULL, 'divorce', 137, true, '6 months state residency', 30, true, true, ARRAY['Petition for Dissolution'], '{"methods": ["personal", "certified_mail"], "days_to_respond": 30}', true, 'Odyssey', '{"grounds": "incompatibility", "30_day_waiting_period": true}', 'https://www.nmcourts.gov/', CURRENT_DATE),
('NY', NULL, 'divorce', 335, true, '1 year state or 2 years married in NY', 0, true, true, ARRAY['Summons with Notice', 'Verified Complaint'], '{"methods": ["personal", "certified_mail"], "days_to_respond": 20}', true, 'NYSCEF', '{"grounds": "irretrievable_breakdown_6_months", "conversion_divorce_available": true}', 'https://www.nycourts.gov/', CURRENT_DATE),
('NC', NULL, 'divorce', 225, true, '6 months state residency', 365, true, true, ARRAY['Complaint for Absolute Divorce'], '{"methods": ["personal", "certified_mail"], "days_to_respond": 30}', true, 'Odyssey', '{"grounds": "1_year_separation", "bed_and_board_available": true}', 'https://www.nccourts.gov/', CURRENT_DATE),
('ND', NULL, 'divorce', 80, true, '6 months state residency', 0, true, true, ARRAY['Complaint for Divorce'], '{"methods": ["personal", "certified_mail"], "days_to_respond": 20}', true, 'Odyssey', '{"grounds": "irreconcilable_differences", "fault_grounds_available": true}', 'https://www.ndcourts.gov/', CURRENT_DATE),
('OH', NULL, 'divorce', 350, true, '6 months state residency', 0, false, true, ARRAY['Complaint for Divorce'], '{"methods": ["personal", "certified_mail"], "days_to_respond": 28}', true, 'Various by county', '{"grounds": "incompatibility", "dissolution_available": true}', 'https://www.supremecourt.ohio.gov/', CURRENT_DATE),
('OK', NULL, 'divorce', 183, true, '6 months state residency', 10, false, true, ARRAY['Petition for Dissolution'], '{"methods": ["personal", "certified_mail"], "days_to_respond": 20}', true, 'Oklahoma eFiling', '{"grounds": "incompatibility", "10_day_waiting_period": true}', 'https://www.oscn.net/', CURRENT_DATE),
('OR', NULL, 'divorce', 301, true, '6 months state residency', 90, true, true, ARRAY['Petition for Dissolution'], '{"methods": ["personal", "certified_mail"], "days_to_respond": 30}', true, 'Oregon eCourt', '{"grounds": "irreconcilable_differences", "90_day_waiting_if_children": true}', 'https://www.courts.oregon.gov/', CURRENT_DATE),
('PA', NULL, 'divorce', 333, true, '6 months state residency', 90, true, true, ARRAY['Complaint in Divorce'], '{"methods": ["personal", "certified_mail"], "days_to_respond": 20}', true, 'PACFile', '{"grounds": "irretrievable_breakdown", "mutual_consent_or_2_year_separation": true}', 'https://www.pacourts.us/', CURRENT_DATE),
('RI', NULL, 'divorce', 160, true, '1 year state residency', 0, false, true, ARRAY['Complaint for Divorce'], '{"methods": ["personal", "certified_mail"], "days_to_respond": 20}', true, 'File & Serve', '{"grounds": "irreconcilable_differences", "nominal_hearing_required": true}', 'https://www.courts.ri.gov/', CURRENT_DATE),
('SC', NULL, 'divorce', 150, true, '3 months if both residents, 1 year otherwise', 0, true, true, ARRAY['Complaint for Divorce'], '{"methods": ["personal", "certified_mail"], "days_to_respond": 30}', true, 'SC Courts eFiling', '{"grounds": "no_fault_1_year_separation", "fault_grounds_available": true}', 'https://www.sccourts.org/', CURRENT_DATE),
('SD', NULL, 'divorce', 95, true, 'State resident at filing', 60, true, true, ARRAY['Complaint for Divorce'], '{"methods": ["personal", "certified_mail"], "days_to_respond": 30}', true, 'Odyssey', '{"grounds": "irreconcilable_differences", "60_day_waiting_period": true}', 'https://ujs.sd.gov/', CURRENT_DATE),
('TN', NULL, 'divorce', 305, true, '6 months state residency', 60, true, true, ARRAY['Complaint for Divorce'], '{"methods": ["personal", "certified_mail"], "days_to_respond": 30}', true, 'Odyssey', '{"grounds": "irreconcilable_differences", "60_or_90_day_waiting": true}', 'https://www.tncourts.gov/', CURRENT_DATE),
('TX', NULL, 'divorce', 350, true, '6 months state, 90 days county', 60, true, true, ARRAY['Original Petition for Divorce'], '{"methods": ["personal", "certified_mail"], "days_to_respond": 20}', true, 'eFileTexas', '{"grounds": "insupportability", "60_day_waiting_period": true}', 'https://www.txcourts.gov/', CURRENT_DATE),
('UT', NULL, 'divorce', 325, true, '3 months county residency', 90, true, true, ARRAY['Petition for Divorce'], '{"methods": ["personal", "certified_mail"], "days_to_respond": 21}', true, 'Utah Courts OCAP', '{"grounds": "irreconcilable_differences", "90_day_waiting_period": true}', 'https://www.utcourts.gov/', CURRENT_DATE),
('VT', NULL, 'divorce', 295, true, '6 months state residency', 0, false, true, ARRAY['Complaint for Divorce'], '{"methods": ["personal", "certified_mail"], "days_to_respond": 20}', true, 'Odyssey', '{"grounds": "living_apart_6_months", "fault_grounds_available": true}', 'https://www.vermontjudiciary.org/', CURRENT_DATE),
('VA', NULL, 'divorce', 86, true, '6 months state residency', 0, false, true, ARRAY['Complaint for Divorce'], '{"methods": ["personal", "certified_mail"], "days_to_respond": 21}', true, 'VSCMS', '{"grounds": "no_fault_1_year_separation", "6_months_if_no_children_and_agreement": true}', 'https://www.vacourts.gov/', CURRENT_DATE),
('WA', NULL, 'divorce', 350, true, 'Washington domicile', 90, true, true, ARRAY['Petition for Dissolution'], '{"methods": ["personal", "certified_mail"], "days_to_respond": 20}', true, 'Various by county', '{"grounds": "irretrievable_breakdown", "90_day_waiting_period": true}', 'https://www.courts.wa.gov/', CURRENT_DATE),
('WV', NULL, 'divorce', 200, true, '1 year state or married in WV', 20, false, true, ARRAY['Petition for Divorce'], '{"methods": ["personal", "certified_mail"], "days_to_respond": 20}', true, 'E-Filing WV', '{"grounds": "irreconcilable_differences", "fault_grounds_available": true}', 'https://www.courtswv.gov/', CURRENT_DATE),
('WI', NULL, 'divorce', 184, true, '6 months state, 30 days county', 120, true, true, ARRAY['Summons and Petition'], '{"methods": ["personal", "certified_mail"], "days_to_respond": 20}', true, 'eFiling Wisconsin', '{"grounds": "irretrievable_breakdown", "120_day_waiting_period": true}', 'https://www.wicourts.gov/', CURRENT_DATE),
('WY', NULL, 'divorce', 70, true, '60 days state residency', 20, false, true, ARRAY['Complaint for Divorce'], '{"methods": ["personal", "certified_mail"], "days_to_respond": 20}', true, 'Wyoming eCourt', '{"grounds": "irreconcilable_differences", "20_day_waiting_period": true}', 'https://www.courts.state.wy.us/', CURRENT_DATE),
('DC', NULL, 'divorce', 120, true, '6 months DC residency', 0, true, true, ARRAY['Complaint for Divorce'], '{"methods": ["personal", "certified_mail"], "days_to_respond": 20}', true, 'DC Superior Court E-Filing', '{"grounds": "mutual_voluntary_separation", "6_month_or_1_year_separation": true}', 'https://www.dccourts.gov/', CURRENT_DATE)
ON CONFLICT (state_code, county, filing_type) DO UPDATE SET
  filing_fee = EXCLUDED.filing_fee,
  fee_waiver_available = EXCLUDED.fee_waiver_available,
  residency_requirement = EXCLUDED.residency_requirement,
  waiting_period_days = EXCLUDED.waiting_period_days,
  mandatory_mediation = EXCLUDED.mandatory_mediation,
  mandatory_parenting_class = EXCLUDED.mandatory_parenting_class,
  required_forms = EXCLUDED.required_forms,
  service_requirements = EXCLUDED.service_requirements,
  efiling_available = EXCLUDED.efiling_available,
  efiling_system = EXCLUDED.efiling_system,
  special_rules = EXCLUDED.special_rules,
  source_url = EXCLUDED.source_url,
  last_verified = EXCLUDED.last_verified,
  updated_at = NOW();

-- Log the ingestion
INSERT INTO lf_data_ingestion_log (data_type, source, records_processed, records_created, status, completed_at, metadata)
VALUES ('filing_requirements', 'manual_seed', 51, 51, 'completed', NOW(), '{"states_covered": 51, "filing_type": "divorce"}');

