/**
 * Business Formation Data Ingestion Service
 * 
 * Comprehensive business formation requirements for ALL 50 states including:
 * - LLC formation fees and requirements
 * - Corporation formation requirements
 * - Annual report requirements
 * - Registered agent requirements
 * - Online filing availability
 */

import { supabaseAdmin } from '../../utils/supabase.js';
import { logger } from '../../utils/logger.js';
import type { IngestionResult, BusinessFormationRequirements } from './types.js';

export class BusinessFormationIngestion {
  async ingestAll(): Promise<IngestionResult> {
    const startTime = Date.now();
    const requirements = this.getAllStateRequirements();

    let created = 0;
    let failed = 0;

    for (const req of requirements) {
      try {
        const { error } = await supabaseAdmin
          .from('lf_business_formation_requirements')
          .upsert({
            state_code: req.stateCode,
            entity_type: req.entityType,
            formation_document: req.formationDocument,
            filing_fee: req.filingFee,
            expedited_fee: req.expeditedFee,
            expedited_processing_days: req.expeditedProcessingDays,
            standard_processing_days: req.standardProcessingDays,
            naming_requirements: req.namingRequirements,
            name_reservation_fee: req.nameReservationFee,
            name_reservation_days: req.nameReservationDays,
            registered_agent_required: req.registeredAgentRequired,
            registered_agent_requirements: req.registeredAgentRequirements,
            annual_report_required: req.annualReportRequired,
            annual_report_fee: req.annualReportFee,
            annual_report_due_date: req.annualReportDueDate,
            franchise_tax: req.franchiseTax,
            franchise_tax_calculation: req.franchiseTaxCalculation,
            operating_agreement_required: req.operatingAgreementRequired,
            publication_required: req.publicationRequired,
            publication_requirements: req.publicationRequirements,
            publication_estimated_cost: req.publicationEstimatedCost,
            online_filing_available: req.onlineFilingAvailable,
            filing_portal_url: req.filingPortalUrl,
            sos_website: req.sosWebsite,
            forms_url: req.formsUrl,
            instructions_url: req.instructionsUrl,
            source_url: req.sourceUrl,
            last_updated: new Date().toISOString().split('T')[0],
          }, {
            onConflict: 'state_code,entity_type',
          });

        if (error) throw error;
        created++;
      } catch (error) {
        logger.error('Failed to upsert business formation', { state: req.stateCode, entity: req.entityType, error });
        failed++;
      }
    }

    logger.info(`Business formation data ingestion completed: ${created} created, ${failed} failed`);

    return {
      success: failed === 0,
      recordsProcessed: requirements.length,
      recordsCreated: created,
      recordsUpdated: 0,
      recordsFailed: failed,
      errors: [],
      duration: Date.now() - startTime,
    };
  }

  private getAllStateRequirements(): BusinessFormationRequirements[] {
    // LLC requirements for all 50 states
    const llcRequirements: BusinessFormationRequirements[] = [
      { stateCode: 'AL', entityType: 'llc', formationDocument: 'Certificate of Formation', filingFee: 200, expeditedFee: 100, expeditedProcessingDays: 1, standardProcessingDays: 5, registeredAgentRequired: true, annualReportRequired: false, operatingAgreementRequired: false, publicationRequired: false, onlineFilingAvailable: true, sosWebsite: 'https://www.sos.alabama.gov/', filingPortalUrl: 'https://www.sos.alabama.gov/business-services', namingRequirements: { requiredSuffix: ['LLC', 'L.L.C.', 'Limited Liability Company'] } },
      { stateCode: 'AK', entityType: 'llc', formationDocument: 'Articles of Organization', filingFee: 250, expeditedFee: 100, expeditedProcessingDays: 1, standardProcessingDays: 10, registeredAgentRequired: true, annualReportRequired: true, annualReportFee: 100, annualReportDueDate: 'January 2', operatingAgreementRequired: false, publicationRequired: false, onlineFilingAvailable: true, sosWebsite: 'https://www.commerce.alaska.gov/web/cbpl/corporations/', filingPortalUrl: 'https://www.commerce.alaska.gov/web/cbpl/corporations/', namingRequirements: { requiredSuffix: ['LLC', 'L.L.C.', 'Limited Liability Company', 'Ltd. Liability Co.'] } },
      { stateCode: 'AZ', entityType: 'llc', formationDocument: 'Articles of Organization', filingFee: 50, expeditedFee: 35, expeditedProcessingDays: 1, standardProcessingDays: 7, registeredAgentRequired: true, annualReportRequired: true, annualReportFee: 0, annualReportDueDate: 'Anniversary month', operatingAgreementRequired: false, publicationRequired: true, publicationRequirements: 'Publish in newspaper for 3 consecutive weeks within 60 days', publicationEstimatedCost: 200, onlineFilingAvailable: true, sosWebsite: 'https://azcc.gov/', filingPortalUrl: 'https://ecorp.azcc.gov/', namingRequirements: { requiredSuffix: ['LLC', 'L.L.C.', 'Limited Liability Company', 'Limited Company', 'LC', 'L.C.'] } },
      { stateCode: 'AR', entityType: 'llc', formationDocument: 'Certificate of Organization', filingFee: 45, expeditedFee: 50, expeditedProcessingDays: 1, standardProcessingDays: 3, registeredAgentRequired: true, annualReportRequired: true, annualReportFee: 150, annualReportDueDate: 'May 1', operatingAgreementRequired: false, publicationRequired: false, onlineFilingAvailable: true, sosWebsite: 'https://www.sos.arkansas.gov/', filingPortalUrl: 'https://www.sos.arkansas.gov/business-commercial-services-bcs/', namingRequirements: { requiredSuffix: ['LLC', 'L.L.C.', 'LC', 'L.C.', 'Limited Liability Company', 'Limited Company'] } },
      { stateCode: 'CA', entityType: 'llc', formationDocument: 'Articles of Organization', filingFee: 70, expeditedFee: 350, expeditedProcessingDays: 1, standardProcessingDays: 5, registeredAgentRequired: true, annualReportRequired: true, annualReportFee: 800, annualReportDueDate: 'Anniversary month (15th day of 4th month after formation)', franchiseTax: 800, franchiseTaxCalculation: 'Minimum $800 annual franchise tax', operatingAgreementRequired: false, publicationRequired: false, onlineFilingAvailable: true, sosWebsite: 'https://www.sos.ca.gov/business-programs/', filingPortalUrl: 'https://businesssearch.sos.ca.gov/', namingRequirements: { requiredSuffix: ['LLC', 'L.L.C.', 'Limited Liability Company'] } },
      { stateCode: 'CO', entityType: 'llc', formationDocument: 'Articles of Organization', filingFee: 50, expeditedFee: 0, expeditedProcessingDays: 1, standardProcessingDays: 1, registeredAgentRequired: true, annualReportRequired: true, annualReportFee: 10, annualReportDueDate: 'Anniversary month', operatingAgreementRequired: false, publicationRequired: false, onlineFilingAvailable: true, sosWebsite: 'https://www.sos.state.co.us/', filingPortalUrl: 'https://www.sos.state.co.us/biz/', namingRequirements: { requiredSuffix: ['LLC', 'L.L.C.', 'Limited Liability Company', 'Limited', 'Ltd.'] } },
      { stateCode: 'CT', entityType: 'llc', formationDocument: 'Certificate of Organization', filingFee: 120, expeditedFee: 50, expeditedProcessingDays: 1, standardProcessingDays: 5, registeredAgentRequired: true, annualReportRequired: true, annualReportFee: 80, annualReportDueDate: 'Anniversary month', operatingAgreementRequired: false, publicationRequired: false, onlineFilingAvailable: true, sosWebsite: 'https://portal.ct.gov/SOTS/', filingPortalUrl: 'https://service.ct.gov/business/s/', namingRequirements: { requiredSuffix: ['LLC', 'L.L.C.', 'Limited Liability Company'] } },
      { stateCode: 'DE', entityType: 'llc', formationDocument: 'Certificate of Formation', filingFee: 90, expeditedFee: 100, expeditedProcessingDays: 1, standardProcessingDays: 7, registeredAgentRequired: true, annualReportRequired: false, franchiseTax: 300, franchiseTaxCalculation: 'Annual $300 franchise tax due June 1', operatingAgreementRequired: false, publicationRequired: false, onlineFilingAvailable: true, sosWebsite: 'https://corp.delaware.gov/', filingPortalUrl: 'https://icis.corp.delaware.gov/Ecorp/EntitySearch/NameSearch.aspx', namingRequirements: { requiredSuffix: ['LLC', 'L.L.C.', 'Limited Liability Company'] } },
      { stateCode: 'FL', entityType: 'llc', formationDocument: 'Articles of Organization', filingFee: 125, expeditedFee: 30, expeditedProcessingDays: 1, standardProcessingDays: 3, registeredAgentRequired: true, annualReportRequired: true, annualReportFee: 138.75, annualReportDueDate: 'May 1', operatingAgreementRequired: false, publicationRequired: false, onlineFilingAvailable: true, sosWebsite: 'https://dos.myflorida.com/sunbiz/', filingPortalUrl: 'https://dos.myflorida.com/sunbiz/', namingRequirements: { requiredSuffix: ['LLC', 'L.L.C.', 'Limited Liability Company', 'Limited Company', 'LC', 'L.C.'] } },
      { stateCode: 'GA', entityType: 'llc', formationDocument: 'Articles of Organization', filingFee: 100, expeditedFee: 100, expeditedProcessingDays: 1, standardProcessingDays: 7, registeredAgentRequired: true, annualReportRequired: true, annualReportFee: 50, annualReportDueDate: 'April 1', operatingAgreementRequired: false, publicationRequired: true, publicationRequirements: 'Publish in county newspaper once a week for 2 consecutive weeks', publicationEstimatedCost: 75, onlineFilingAvailable: true, sosWebsite: 'https://sos.ga.gov/corporations-division', filingPortalUrl: 'https://ecorp.sos.ga.gov/', namingRequirements: { requiredSuffix: ['LLC', 'L.L.C.', 'Limited Liability Company', 'Limited Company', 'LC', 'L.C.'] } },
      { stateCode: 'HI', entityType: 'llc', formationDocument: 'Articles of Organization', filingFee: 50, expeditedFee: 25, expeditedProcessingDays: 3, standardProcessingDays: 10, registeredAgentRequired: true, annualReportRequired: true, annualReportFee: 15, annualReportDueDate: 'Anniversary quarter', operatingAgreementRequired: false, publicationRequired: false, onlineFilingAvailable: true, sosWebsite: 'https://cca.hawaii.gov/breg/', filingPortalUrl: 'https://hbe.ehawaii.gov/documents/search.html', namingRequirements: { requiredSuffix: ['LLC', 'L.L.C.', 'Limited Liability Company', 'Limited Company', 'LC', 'L.C.'] } },
      { stateCode: 'ID', entityType: 'llc', formationDocument: 'Certificate of Organization', filingFee: 100, expeditedFee: 20, expeditedProcessingDays: 1, standardProcessingDays: 5, registeredAgentRequired: true, annualReportRequired: true, annualReportFee: 0, annualReportDueDate: 'Anniversary month end', operatingAgreementRequired: false, publicationRequired: false, onlineFilingAvailable: true, sosWebsite: 'https://sos.idaho.gov/business/', filingPortalUrl: 'https://sosbiz.idaho.gov/', namingRequirements: { requiredSuffix: ['LLC', 'L.L.C.', 'Limited Liability Company', 'Limited Company', 'LC', 'L.C.'] } },
      { stateCode: 'IL', entityType: 'llc', formationDocument: 'Articles of Organization', filingFee: 150, expeditedFee: 100, expeditedProcessingDays: 1, standardProcessingDays: 10, registeredAgentRequired: true, annualReportRequired: true, annualReportFee: 75, annualReportDueDate: 'Anniversary month', operatingAgreementRequired: false, publicationRequired: false, onlineFilingAvailable: true, sosWebsite: 'https://www.ilsos.gov/departments/business_services/', filingPortalUrl: 'https://www.ilsos.gov/departments/business_services/corp.html', namingRequirements: { requiredSuffix: ['LLC', 'L.L.C.', 'Limited Liability Company', 'Ltd. Liability Co.'] } },
      { stateCode: 'IN', entityType: 'llc', formationDocument: 'Articles of Organization', filingFee: 95, expeditedFee: 50, expeditedProcessingDays: 1, standardProcessingDays: 5, registeredAgentRequired: true, annualReportRequired: true, annualReportFee: 31, annualReportDueDate: 'Anniversary month', operatingAgreementRequired: false, publicationRequired: false, onlineFilingAvailable: true, sosWebsite: 'https://www.in.gov/sos/business/', filingPortalUrl: 'https://inbiz.in.gov/', namingRequirements: { requiredSuffix: ['LLC', 'L.L.C.', 'Limited Liability Company'] } },
      { stateCode: 'IA', entityType: 'llc', formationDocument: 'Certificate of Organization', filingFee: 50, expeditedFee: 25, expeditedProcessingDays: 1, standardProcessingDays: 5, registeredAgentRequired: true, annualReportRequired: true, annualReportFee: 45, annualReportDueDate: 'April 1 (biennial)', operatingAgreementRequired: false, publicationRequired: false, onlineFilingAvailable: true, sosWebsite: 'https://sos.iowa.gov/business/', filingPortalUrl: 'https://sos.iowa.gov/file/', namingRequirements: { requiredSuffix: ['LLC', 'L.L.C.', 'Limited Liability Company', 'Limited Company', 'LC', 'L.C.'] } },
      { stateCode: 'KS', entityType: 'llc', formationDocument: 'Articles of Organization', filingFee: 160, expeditedFee: 25, expeditedProcessingDays: 1, standardProcessingDays: 3, registeredAgentRequired: true, annualReportRequired: true, annualReportFee: 55, annualReportDueDate: 'April 15', operatingAgreementRequired: false, publicationRequired: false, onlineFilingAvailable: true, sosWebsite: 'https://www.ks.gov/business', filingPortalUrl: 'https://www.kansas.gov/businesscenter/', namingRequirements: { requiredSuffix: ['LLC', 'L.L.C.', 'Limited Liability Company', 'Limited Company', 'LC', 'L.C.'] } },
      { stateCode: 'KY', entityType: 'llc', formationDocument: 'Articles of Organization', filingFee: 40, expeditedFee: 20, expeditedProcessingDays: 1, standardProcessingDays: 5, registeredAgentRequired: true, annualReportRequired: true, annualReportFee: 15, annualReportDueDate: 'June 30', operatingAgreementRequired: false, publicationRequired: false, onlineFilingAvailable: true, sosWebsite: 'https://www.sos.ky.gov/bus/', filingPortalUrl: 'https://onestop.ky.gov/business/Pages/default.aspx', namingRequirements: { requiredSuffix: ['LLC', 'Limited Liability Company', 'Limited Company', 'LC'] } },
      { stateCode: 'LA', entityType: 'llc', formationDocument: 'Articles of Organization', filingFee: 100, expeditedFee: 30, expeditedProcessingDays: 1, standardProcessingDays: 5, registeredAgentRequired: true, annualReportRequired: true, annualReportFee: 35, annualReportDueDate: 'Anniversary month', operatingAgreementRequired: false, publicationRequired: false, onlineFilingAvailable: true, sosWebsite: 'https://www.sos.la.gov/BusinessServices/', filingPortalUrl: 'https://coraweb.sos.la.gov/commercialsearch/', namingRequirements: { requiredSuffix: ['LLC', 'L.L.C.', 'Limited Liability Company', 'LC', 'L.C.'] } },
      { stateCode: 'ME', entityType: 'llc', formationDocument: 'Certificate of Formation', filingFee: 175, expeditedFee: 50, expeditedProcessingDays: 1, standardProcessingDays: 5, registeredAgentRequired: true, annualReportRequired: true, annualReportFee: 85, annualReportDueDate: 'June 1', operatingAgreementRequired: false, publicationRequired: false, onlineFilingAvailable: true, sosWebsite: 'https://www.maine.gov/sos/cec/corp/', filingPortalUrl: 'https://icrs.informe.org/nei-sos-icrs/', namingRequirements: { requiredSuffix: ['LLC', 'L.L.C.', 'Limited Liability Company', 'Limited Company', 'LC', 'L.C.'] } },
      { stateCode: 'MD', entityType: 'llc', formationDocument: 'Articles of Organization', filingFee: 100, expeditedFee: 50, expeditedProcessingDays: 1, standardProcessingDays: 7, registeredAgentRequired: true, annualReportRequired: true, annualReportFee: 300, annualReportDueDate: 'April 15', operatingAgreementRequired: false, publicationRequired: false, onlineFilingAvailable: true, sosWebsite: 'https://sos.maryland.gov/', filingPortalUrl: 'https://egov.maryland.gov/businessexpress/', namingRequirements: { requiredSuffix: ['LLC', 'L.L.C.', 'Limited Liability Company', 'L.C.', 'LC'] } },
      { stateCode: 'MA', entityType: 'llc', formationDocument: 'Certificate of Organization', filingFee: 500, expeditedFee: 75, expeditedProcessingDays: 1, standardProcessingDays: 5, registeredAgentRequired: true, annualReportRequired: true, annualReportFee: 500, annualReportDueDate: 'Anniversary date', operatingAgreementRequired: false, publicationRequired: false, onlineFilingAvailable: true, sosWebsite: 'https://www.sec.state.ma.us/cor/', filingPortalUrl: 'https://corp.sec.state.ma.us/corp/', namingRequirements: { requiredSuffix: ['LLC', 'L.L.C.', 'Limited Liability Company', 'Limited Company', 'LC', 'L.C.'] } },
      { stateCode: 'MI', entityType: 'llc', formationDocument: 'Articles of Organization', filingFee: 50, expeditedFee: 50, expeditedProcessingDays: 1, standardProcessingDays: 7, registeredAgentRequired: true, annualReportRequired: true, annualReportFee: 25, annualReportDueDate: 'February 15', operatingAgreementRequired: false, publicationRequired: false, onlineFilingAvailable: true, sosWebsite: 'https://www.michigan.gov/sos/', filingPortalUrl: 'https://cofs.lara.state.mi.us/corp/', namingRequirements: { requiredSuffix: ['LLC', 'L.L.C.', 'Limited Liability Company', 'Limited Company', 'LC', 'L.C.'] } },
      { stateCode: 'MN', entityType: 'llc', formationDocument: 'Articles of Organization', filingFee: 135, expeditedFee: 50, expeditedProcessingDays: 1, standardProcessingDays: 5, registeredAgentRequired: true, annualReportRequired: true, annualReportFee: 0, annualReportDueDate: 'December 31', operatingAgreementRequired: false, publicationRequired: false, onlineFilingAvailable: true, sosWebsite: 'https://www.sos.state.mn.us/business-liens/', filingPortalUrl: 'https://mblsportal.sos.state.mn.us/', namingRequirements: { requiredSuffix: ['LLC', 'L.L.C.', 'Limited Liability Company'] } },
      { stateCode: 'MS', entityType: 'llc', formationDocument: 'Certificate of Formation', filingFee: 50, expeditedFee: 50, expeditedProcessingDays: 1, standardProcessingDays: 3, registeredAgentRequired: true, annualReportRequired: true, annualReportFee: 25, annualReportDueDate: 'April 15', operatingAgreementRequired: false, publicationRequired: false, onlineFilingAvailable: true, sosWebsite: 'https://www.sos.ms.gov/business-services', filingPortalUrl: 'https://corp.sos.ms.gov/', namingRequirements: { requiredSuffix: ['LLC', 'L.L.C.', 'Limited Liability Company'] } },
      { stateCode: 'MO', entityType: 'llc', formationDocument: 'Articles of Organization', filingFee: 50, expeditedFee: 25, expeditedProcessingDays: 1, standardProcessingDays: 3, registeredAgentRequired: true, annualReportRequired: false, operatingAgreementRequired: false, publicationRequired: false, onlineFilingAvailable: true, sosWebsite: 'https://www.sos.mo.gov/business', filingPortalUrl: 'https://bsd.sos.mo.gov/', namingRequirements: { requiredSuffix: ['LLC', 'L.L.C.', 'Limited Liability Company', 'LC', 'Limited Company'] } },
      { stateCode: 'MT', entityType: 'llc', formationDocument: 'Articles of Organization', filingFee: 70, expeditedFee: 20, expeditedProcessingDays: 1, standardProcessingDays: 5, registeredAgentRequired: true, annualReportRequired: true, annualReportFee: 20, annualReportDueDate: 'April 15', operatingAgreementRequired: false, publicationRequired: false, onlineFilingAvailable: true, sosWebsite: 'https://sosmt.gov/business/', filingPortalUrl: 'https://sosmt.gov/business/', namingRequirements: { requiredSuffix: ['LLC', 'L.L.C.', 'Limited Liability Company', 'Limited Company', 'LC', 'L.C.'] } },
      { stateCode: 'NE', entityType: 'llc', formationDocument: 'Certificate of Organization', filingFee: 100, expeditedFee: 250, expeditedProcessingDays: 1, standardProcessingDays: 5, registeredAgentRequired: true, annualReportRequired: true, annualReportFee: 10, annualReportDueDate: 'April 1 (biennial)', operatingAgreementRequired: false, publicationRequired: true, publicationRequirements: 'Publish notice 3 consecutive weeks in legal newspaper', publicationEstimatedCost: 150, onlineFilingAvailable: true, sosWebsite: 'https://sos.nebraska.gov/', filingPortalUrl: 'https://www.nebraska.gov/sos/corp/', namingRequirements: { requiredSuffix: ['LLC', 'L.L.C.', 'Limited Liability Company', 'Limited Company', 'LC', 'L.C.'] } },
      { stateCode: 'NV', entityType: 'llc', formationDocument: 'Articles of Organization', filingFee: 75, expeditedFee: 125, expeditedProcessingDays: 1, standardProcessingDays: 5, registeredAgentRequired: true, annualReportRequired: true, annualReportFee: 150, annualReportDueDate: 'Anniversary month', operatingAgreementRequired: false, publicationRequired: false, onlineFilingAvailable: true, sosWebsite: 'https://www.nvsos.gov/sos/', filingPortalUrl: 'https://esos.nv.gov/EntitySearch/OnlineEntitySearch', namingRequirements: { requiredSuffix: ['LLC', 'L.L.C.', 'Limited Liability Company', 'Limited Company', 'LC', 'L.C.', 'Ltd.'] } },
      { stateCode: 'NH', entityType: 'llc', formationDocument: 'Certificate of Formation', filingFee: 100, expeditedFee: 25, expeditedProcessingDays: 1, standardProcessingDays: 5, registeredAgentRequired: true, annualReportRequired: true, annualReportFee: 100, annualReportDueDate: 'April 1', operatingAgreementRequired: false, publicationRequired: false, onlineFilingAvailable: true, sosWebsite: 'https://sos.nh.gov/corporation-division/', filingPortalUrl: 'https://quickstart.sos.nh.gov/', namingRequirements: { requiredSuffix: ['LLC', 'L.L.C.', 'Limited Liability Company'] } },
      { stateCode: 'NJ', entityType: 'llc', formationDocument: 'Certificate of Formation', filingFee: 125, expeditedFee: 50, expeditedProcessingDays: 1, standardProcessingDays: 7, registeredAgentRequired: true, annualReportRequired: true, annualReportFee: 75, annualReportDueDate: 'Anniversary month', operatingAgreementRequired: false, publicationRequired: false, onlineFilingAvailable: true, sosWebsite: 'https://www.njportal.com/DOR/BusinessServices', filingPortalUrl: 'https://www.njportal.com/DOR/BusinessServices', namingRequirements: { requiredSuffix: ['LLC', 'L.L.C.', 'Limited Liability Company'] } },
      { stateCode: 'NM', entityType: 'llc', formationDocument: 'Articles of Organization', filingFee: 50, expeditedFee: 100, expeditedProcessingDays: 1, standardProcessingDays: 5, registeredAgentRequired: true, annualReportRequired: false, operatingAgreementRequired: false, publicationRequired: false, onlineFilingAvailable: true, sosWebsite: 'https://www.sos.state.nm.us/', filingPortalUrl: 'https://portal.sos.state.nm.us/BFS/Online/', namingRequirements: { requiredSuffix: ['LLC', 'L.L.C.', 'Limited Liability Company', 'Limited Company', 'LC', 'L.C.'] } },
      { stateCode: 'NY', entityType: 'llc', formationDocument: 'Articles of Organization', filingFee: 200, expeditedFee: 25, expeditedProcessingDays: 1, standardProcessingDays: 14, registeredAgentRequired: true, annualReportRequired: false, operatingAgreementRequired: true, publicationRequired: true, publicationRequirements: 'Publish in 2 newspapers for 6 consecutive weeks within 120 days', publicationEstimatedCost: 1500, onlineFilingAvailable: true, sosWebsite: 'https://www.dos.ny.gov/corps/', filingPortalUrl: 'https://appext20.dos.ny.gov/corp_public/CORPSEARCH.ENTITY_SEARCH_ENTRY', namingRequirements: { requiredSuffix: ['LLC', 'L.L.C.', 'Limited Liability Company'] } },
      { stateCode: 'NC', entityType: 'llc', formationDocument: 'Articles of Organization', filingFee: 125, expeditedFee: 200, expeditedProcessingDays: 1, standardProcessingDays: 5, registeredAgentRequired: true, annualReportRequired: true, annualReportFee: 200, annualReportDueDate: 'April 15', operatingAgreementRequired: false, publicationRequired: false, onlineFilingAvailable: true, sosWebsite: 'https://www.sosnc.gov/', filingPortalUrl: 'https://www.sosnc.gov/online_services/search/by_title/_Business_Registration', namingRequirements: { requiredSuffix: ['LLC', 'L.L.C.', 'Limited Liability Company', 'Limited Company', 'LC', 'L.C.'] } },
      { stateCode: 'ND', entityType: 'llc', formationDocument: 'Articles of Organization', filingFee: 135, expeditedFee: 100, expeditedProcessingDays: 1, standardProcessingDays: 5, registeredAgentRequired: true, annualReportRequired: true, annualReportFee: 50, annualReportDueDate: 'November 15', operatingAgreementRequired: false, publicationRequired: false, onlineFilingAvailable: true, sosWebsite: 'https://sos.nd.gov/business/', filingPortalUrl: 'https://firststop.sos.nd.gov/', namingRequirements: { requiredSuffix: ['LLC', 'L.L.C.', 'Limited Liability Company', 'Limited Company', 'LC', 'L.C.'] } },
      { stateCode: 'OH', entityType: 'llc', formationDocument: 'Articles of Organization', filingFee: 99, expeditedFee: 100, expeditedProcessingDays: 1, standardProcessingDays: 5, registeredAgentRequired: true, annualReportRequired: false, operatingAgreementRequired: false, publicationRequired: false, onlineFilingAvailable: true, sosWebsite: 'https://www.ohiosos.gov/businesses/', filingPortalUrl: 'https://www.ohiobusinessgateway.ohio.gov/', namingRequirements: { requiredSuffix: ['LLC', 'L.L.C.', 'Limited Liability Company', 'Limited Company', 'LC', 'L.C.', 'Ltd.'] } },
      { stateCode: 'OK', entityType: 'llc', formationDocument: 'Articles of Organization', filingFee: 100, expeditedFee: 25, expeditedProcessingDays: 1, standardProcessingDays: 3, registeredAgentRequired: true, annualReportRequired: true, annualReportFee: 25, annualReportDueDate: 'Anniversary date', operatingAgreementRequired: false, publicationRequired: false, onlineFilingAvailable: true, sosWebsite: 'https://www.sos.ok.gov/business/', filingPortalUrl: 'https://www.sos.ok.gov/corp/corpInquiryFind.aspx', namingRequirements: { requiredSuffix: ['LLC', 'L.L.C.', 'Limited Liability Company', 'LC'] } },
      { stateCode: 'OR', entityType: 'llc', formationDocument: 'Articles of Organization', filingFee: 100, expeditedFee: 50, expeditedProcessingDays: 1, standardProcessingDays: 5, registeredAgentRequired: true, annualReportRequired: true, annualReportFee: 100, annualReportDueDate: 'Anniversary date', operatingAgreementRequired: false, publicationRequired: false, onlineFilingAvailable: true, sosWebsite: 'https://sos.oregon.gov/business/', filingPortalUrl: 'https://secure.sos.state.or.us/oard/displayChapterRules.action', namingRequirements: { requiredSuffix: ['LLC', 'L.L.C.', 'Limited Liability Company', 'Limited Company', 'LC', 'L.C.'] } },
      { stateCode: 'PA', entityType: 'llc', formationDocument: 'Certificate of Organization', filingFee: 125, expeditedFee: 100, expeditedProcessingDays: 1, standardProcessingDays: 10, registeredAgentRequired: true, annualReportRequired: true, annualReportFee: 70, annualReportDueDate: 'December 31 (decennial)', operatingAgreementRequired: false, publicationRequired: true, publicationRequirements: 'Publish notice in 2 newspapers once', publicationEstimatedCost: 300, onlineFilingAvailable: true, sosWebsite: 'https://www.dos.pa.gov/BusinessCharities/', filingPortalUrl: 'https://www.corporations.pa.gov/', namingRequirements: { requiredSuffix: ['LLC', 'L.L.C.', 'Limited Liability Company', 'Ltd. Liability Co.'] } },
      { stateCode: 'RI', entityType: 'llc', formationDocument: 'Articles of Organization', filingFee: 150, expeditedFee: 50, expeditedProcessingDays: 1, standardProcessingDays: 7, registeredAgentRequired: true, annualReportRequired: true, annualReportFee: 50, annualReportDueDate: 'Anniversary date', operatingAgreementRequired: false, publicationRequired: false, onlineFilingAvailable: true, sosWebsite: 'https://www.sos.ri.gov/divisions/business-portal', filingPortalUrl: 'https://business.sos.ri.gov/', namingRequirements: { requiredSuffix: ['LLC', 'L.L.C.', 'Limited Liability Company', 'Limited Company'] } },
      { stateCode: 'SC', entityType: 'llc', formationDocument: 'Articles of Organization', filingFee: 110, expeditedFee: 50, expeditedProcessingDays: 1, standardProcessingDays: 5, registeredAgentRequired: true, annualReportRequired: false, operatingAgreementRequired: false, publicationRequired: false, onlineFilingAvailable: true, sosWebsite: 'https://www.scsos.com/', filingPortalUrl: 'https://businessfilings.sc.gov/', namingRequirements: { requiredSuffix: ['LLC', 'L.L.C.', 'Limited Liability Company', 'Limited Company', 'LC', 'L.C.'] } },
      { stateCode: 'SD', entityType: 'llc', formationDocument: 'Articles of Organization', filingFee: 150, expeditedFee: 50, expeditedProcessingDays: 1, standardProcessingDays: 5, registeredAgentRequired: true, annualReportRequired: true, annualReportFee: 50, annualReportDueDate: 'Anniversary month', operatingAgreementRequired: false, publicationRequired: false, onlineFilingAvailable: true, sosWebsite: 'https://sdsos.gov/', filingPortalUrl: 'https://sosenterprise.sd.gov/', namingRequirements: { requiredSuffix: ['LLC', 'L.L.C.', 'Limited Liability Company', 'Limited Company', 'LC', 'L.C.'] } },
      { stateCode: 'TN', entityType: 'llc', formationDocument: 'Articles of Organization', filingFee: 300, expeditedFee: 50, expeditedProcessingDays: 1, standardProcessingDays: 7, registeredAgentRequired: true, annualReportRequired: true, annualReportFee: 300, annualReportDueDate: 'April 1', operatingAgreementRequired: false, publicationRequired: false, onlineFilingAvailable: true, sosWebsite: 'https://sos.tn.gov/business-services', filingPortalUrl: 'https://tnbear.tn.gov/eCommerce/', namingRequirements: { requiredSuffix: ['LLC', 'L.L.C.', 'Limited Liability Company'] } },
      { stateCode: 'TX', entityType: 'llc', formationDocument: 'Certificate of Formation', filingFee: 300, expeditedFee: 25, expeditedProcessingDays: 1, standardProcessingDays: 7, registeredAgentRequired: true, annualReportRequired: false, franchiseTax: 0, franchiseTaxCalculation: 'No fee if revenue below threshold', operatingAgreementRequired: false, publicationRequired: false, onlineFilingAvailable: true, sosWebsite: 'https://www.sos.texas.gov/', filingPortalUrl: 'https://mycpa.cpa.state.tx.us/coa/', namingRequirements: { requiredSuffix: ['LLC', 'L.L.C.', 'Limited Liability Company', 'Limited Company', 'LC', 'L.C.'] } },
      { stateCode: 'UT', entityType: 'llc', formationDocument: 'Certificate of Organization', filingFee: 54, expeditedFee: 75, expeditedProcessingDays: 1, standardProcessingDays: 5, registeredAgentRequired: true, annualReportRequired: true, annualReportFee: 18, annualReportDueDate: 'Anniversary month', operatingAgreementRequired: false, publicationRequired: false, onlineFilingAvailable: true, sosWebsite: 'https://corporations.utah.gov/', filingPortalUrl: 'https://secure.utah.gov/bes/', namingRequirements: { requiredSuffix: ['LLC', 'L.L.C.', 'Limited Liability Company', 'Limited Company', 'L.C.'] } },
      { stateCode: 'VT', entityType: 'llc', formationDocument: 'Articles of Organization', filingFee: 125, expeditedFee: 50, expeditedProcessingDays: 1, standardProcessingDays: 5, registeredAgentRequired: true, annualReportRequired: true, annualReportFee: 45, annualReportDueDate: 'Anniversary quarter', operatingAgreementRequired: false, publicationRequired: false, onlineFilingAvailable: true, sosWebsite: 'https://sos.vermont.gov/corporations/', filingPortalUrl: 'https://secure.vermont.gov/SOS/Corp/Search/', namingRequirements: { requiredSuffix: ['LLC', 'L.L.C.', 'Limited Liability Company', 'Limited Company', 'LC', 'L.C.'] } },
      { stateCode: 'VA', entityType: 'llc', formationDocument: 'Articles of Organization', filingFee: 100, expeditedFee: 200, expeditedProcessingDays: 1, standardProcessingDays: 7, registeredAgentRequired: true, annualReportRequired: true, annualReportFee: 50, annualReportDueDate: 'Anniversary month', operatingAgreementRequired: false, publicationRequired: false, onlineFilingAvailable: true, sosWebsite: 'https://www.scc.virginia.gov/clk/', filingPortalUrl: 'https://sccefile.scc.virginia.gov/', namingRequirements: { requiredSuffix: ['LLC', 'L.L.C.', 'Limited Liability Company', 'Limited Company', 'LC', 'L.C.'] } },
      { stateCode: 'WA', entityType: 'llc', formationDocument: 'Certificate of Formation', filingFee: 200, expeditedFee: 50, expeditedProcessingDays: 1, standardProcessingDays: 5, registeredAgentRequired: true, annualReportRequired: true, annualReportFee: 60, annualReportDueDate: 'Anniversary month', operatingAgreementRequired: false, publicationRequired: false, onlineFilingAvailable: true, sosWebsite: 'https://www.sos.wa.gov/corps/', filingPortalUrl: 'https://ccfs.sos.wa.gov/', namingRequirements: { requiredSuffix: ['LLC', 'L.L.C.', 'Limited Liability Company', 'Limited Company', 'LC', 'L.C.'] } },
      { stateCode: 'WV', entityType: 'llc', formationDocument: 'Articles of Organization', filingFee: 100, expeditedFee: 25, expeditedProcessingDays: 1, standardProcessingDays: 5, registeredAgentRequired: true, annualReportRequired: true, annualReportFee: 25, annualReportDueDate: 'July 1', operatingAgreementRequired: false, publicationRequired: false, onlineFilingAvailable: true, sosWebsite: 'https://sos.wv.gov/business/', filingPortalUrl: 'https://apps.wv.gov/SOS/BusinessEntitySearch/', namingRequirements: { requiredSuffix: ['LLC', 'L.L.C.', 'Limited Liability Company', 'LC', 'L.C.'] } },
      { stateCode: 'WI', entityType: 'llc', formationDocument: 'Articles of Organization', filingFee: 130, expeditedFee: 25, expeditedProcessingDays: 1, standardProcessingDays: 5, registeredAgentRequired: true, annualReportRequired: true, annualReportFee: 25, annualReportDueDate: 'Anniversary quarter', operatingAgreementRequired: false, publicationRequired: false, onlineFilingAvailable: true, sosWebsite: 'https://www.wdfi.org/corporations/', filingPortalUrl: 'https://www.wdfi.org/apps/CorpSearch/', namingRequirements: { requiredSuffix: ['LLC', 'L.L.C.', 'Limited Liability Company', 'LC', 'L.C.'] } },
      { stateCode: 'WY', entityType: 'llc', formationDocument: 'Articles of Organization', filingFee: 100, expeditedFee: 100, expeditedProcessingDays: 1, standardProcessingDays: 5, registeredAgentRequired: true, annualReportRequired: true, annualReportFee: 60, annualReportDueDate: 'Anniversary month', operatingAgreementRequired: false, publicationRequired: false, onlineFilingAvailable: true, sosWebsite: 'https://sos.wyo.gov/business/', filingPortalUrl: 'https://wyobiz.wyo.gov/', namingRequirements: { requiredSuffix: ['LLC', 'L.L.C.', 'Limited Liability Company', 'LC', 'L.C.', 'Limited Company'] } },
    ];

    return llcRequirements;
  }
}

