/**
 * Child Support Data Ingestion Service
 * 
 * Comprehensive child support guidelines for ALL 50 US states including:
 * - Calculation models (income shares, percentage, Melson formula)
 * - Support schedules and percentage rates
 * - Parenting time adjustments
 * - Deviation factors
 * - State-specific rules and resources
 */

import { supabaseAdmin } from '../../utils/supabase.js';
import { logger } from '../../utils/logger.js';
import type { IngestionResult, ChildSupportGuidelines, PercentageRate } from './types.js';

export class ChildSupportDataIngestion {
  async ingestAll(): Promise<IngestionResult> {
    const startTime = Date.now();
    const guidelines = this.getAllStateGuidelines();

    let created = 0;
    let failed = 0;

    for (const guideline of guidelines) {
      try {
        const { error } = await supabaseAdmin
          .from('lf_child_support_guidelines')
          .upsert({
            state_code: guideline.stateCode,
            state_name: guideline.stateName,
            version: guideline.version,
            effective_date: guideline.effectiveDate,
            model: guideline.model,
            minimum_income: guideline.minimumIncome,
            maximum_income: guideline.maximumIncome,
            low_income_threshold: guideline.lowIncomeThreshold,
            self_support_reserve: guideline.selfSupportReserve,
            poverty_level_reference: guideline.povertyLevelReference,
            support_schedule: guideline.supportSchedule,
            percentage_rates: guideline.percentageRates,
            parenting_time_threshold: guideline.parentingTimeThreshold,
            parenting_time_formula: guideline.parentingTimeFormula,
            shared_custody_formula: guideline.sharedCustodyFormula,
            split_custody_formula: guideline.splitCustodyFormula,
            health_insurance_treatment: guideline.healthInsuranceTreatment,
            child_care_treatment: guideline.childCareTreatment,
            extraordinary_expenses_treatment: guideline.extraordinaryExpensesTreatment,
            education_expenses_treatment: guideline.educationExpensesTreatment,
            recognized_deviations: guideline.recognizedDeviations,
            age_adjustment_factors: guideline.ageAdjustmentFactors,
            emancipation_age: guideline.emancipationAge,
            college_support_available: guideline.collegeSupportAvailable,
            multiple_family_adjustment: guideline.multipleFamilyAdjustment,
            imputed_income_rules: guideline.imputedIncomeRules,
            self_employment_rules: guideline.selfEmploymentRules,
            guidelines_url: guideline.guidelinesUrl,
            calculator_url: guideline.calculatorUrl,
            worksheet_url: guideline.worksheetUrl,
            statute_citation: guideline.statuteCitation,
            source_url: guideline.sourceUrl,
            last_verified: new Date().toISOString().split('T')[0],
          }, {
            onConflict: 'state_code,effective_date',
          });

        if (error) throw error;
        created++;
      } catch (error) {
        logger.error('Failed to upsert child support guidelines', { state: guideline.stateCode, error });
        failed++;
      }
    }

    logger.info(`Child support data ingestion completed: ${created} created, ${failed} failed`);

    return {
      success: failed === 0,
      recordsProcessed: guidelines.length,
      recordsCreated: created,
      recordsUpdated: 0,
      recordsFailed: failed,
      errors: [],
      duration: Date.now() - startTime,
    };
  }

  private getAllStateGuidelines(): ChildSupportGuidelines[] {
    return [
      // INCOME SHARES MODEL STATES (38 states)
      {
        stateCode: 'AL',
        stateName: 'Alabama',
        version: '2024',
        effectiveDate: '2024-01-01',
        model: 'income_shares',
        minimumIncome: 0,
        maximumIncome: 20000,
        lowIncomeThreshold: 1291,
        selfSupportReserve: 1291,
        parentingTimeThreshold: 0,
        parentingTimeFormula: 'Standard guidelines apply',
        healthInsuranceTreatment: 'add_on',
        childCareTreatment: 'add_on',
        emancipationAge: 19,
        collegeSupportAvailable: false,
        recognizedDeviations: ['Special needs', 'Extraordinary medical', 'Education expenses', 'Shared custody'],
        guidelinesUrl: 'https://judicial.alabama.gov/library/rules/child_support',
        calculatorUrl: 'https://judicial.alabama.gov/library/child_support_calculator',
        statuteCitation: 'Rule 32, Alabama Rules of Judicial Administration',
      },
      {
        stateCode: 'AZ',
        stateName: 'Arizona',
        version: '2024',
        effectiveDate: '2024-01-01',
        model: 'income_shares',
        minimumIncome: 1160,
        maximumIncome: 30000,
        lowIncomeThreshold: 1160,
        selfSupportReserve: 1160,
        parentingTimeThreshold: 100,
        parentingTimeFormula: 'Adjustment begins at 100 parenting days',
        healthInsuranceTreatment: 'add_on',
        childCareTreatment: 'add_on',
        emancipationAge: 18,
        collegeSupportAvailable: false,
        recognizedDeviations: ['Special needs', 'Extraordinary expenses', 'Parenting time adjustment', 'Educational expenses'],
        guidelinesUrl: 'https://www.azcourts.gov/familylaw/Child-Support-Guidelines',
        calculatorUrl: 'https://www.azcourts.gov/familylaw/Child-Support-Calculator',
        statuteCitation: 'A.R.S. § 25-320',
      },
      {
        stateCode: 'AR',
        stateName: 'Arkansas',
        version: '2024',
        effectiveDate: '2024-01-01',
        model: 'income_shares',
        minimumIncome: 0,
        maximumIncome: 30000,
        lowIncomeThreshold: 1200,
        selfSupportReserve: 1200,
        parentingTimeThreshold: 0,
        healthInsuranceTreatment: 'add_on',
        childCareTreatment: 'add_on',
        emancipationAge: 18,
        collegeSupportAvailable: false,
        recognizedDeviations: ['Extraordinary medical', 'Special needs', 'Assets available', 'Travel expenses'],
        guidelinesUrl: 'https://arcourts.gov/forms-publications/child-support-guidelines',
        calculatorUrl: 'https://child-support.arkansas.gov/',
        statuteCitation: 'Administrative Order No. 10',
      },
      {
        stateCode: 'CA',
        stateName: 'California',
        version: '2024',
        effectiveDate: '2024-01-01',
        model: 'income_shares',
        minimumIncome: 0,
        maximumIncome: 300000,
        lowIncomeThreshold: 1500,
        selfSupportReserve: 1000,
        parentingTimeThreshold: 0,
        parentingTimeFormula: 'CS = K[HN-(H%)(TN)]',
        sharedCustodyFormula: 'Complex formula based on timeshare percentage',
        healthInsuranceTreatment: 'add_on',
        childCareTreatment: 'add_on',
        emancipationAge: 18,
        collegeSupportAvailable: false,
        recognizedDeviations: ['Special needs of child', 'Educational expenses', 'Travel expenses for visitation', 'Uninsured health care costs'],
        guidelinesUrl: 'https://www.courts.ca.gov/selfhelp-support.htm',
        calculatorUrl: 'https://childsupport.ca.gov/guideline-calculator/',
        worksheetUrl: 'https://www.courts.ca.gov/documents/fl150.pdf',
        statuteCitation: 'Family Code §§ 4050-4076',
      },
      {
        stateCode: 'CO',
        stateName: 'Colorado',
        version: '2024',
        effectiveDate: '2024-01-01',
        model: 'income_shares',
        minimumIncome: 0,
        maximumIncome: 30000,
        lowIncomeThreshold: 1100,
        selfSupportReserve: 1100,
        parentingTimeThreshold: 92,
        parentingTimeFormula: 'Overnights >= 92 triggers shared custody calculation',
        healthInsuranceTreatment: 'add_on',
        childCareTreatment: 'add_on',
        emancipationAge: 19,
        collegeSupportAvailable: true,
        recognizedDeviations: ['Special needs', 'Extraordinary medical', 'Education', 'Income imputation'],
        guidelinesUrl: 'https://www.courts.state.co.us/Forms/Forms_List.cfm?Form_Type_ID=95',
        calculatorUrl: 'https://coloradocalculators.com/',
        statuteCitation: 'C.R.S. § 14-10-115',
      },
      {
        stateCode: 'CT',
        stateName: 'Connecticut',
        version: '2024',
        effectiveDate: '2024-01-01',
        model: 'income_shares',
        minimumIncome: 0,
        maximumIncome: 20800,
        lowIncomeThreshold: 1000,
        selfSupportReserve: 1000,
        parentingTimeThreshold: 109,
        parentingTimeFormula: 'Shared physical custody adjustment at 109+ overnights',
        healthInsuranceTreatment: 'add_on',
        childCareTreatment: 'add_on',
        emancipationAge: 18,
        collegeSupportAvailable: true,
        recognizedDeviations: ['Extraordinary expenses', 'Special needs', 'Other dependents', 'Assets'],
        guidelinesUrl: 'https://jud.ct.gov/csform/',
        calculatorUrl: 'https://jud.ct.gov/CSCalculator/',
        statuteCitation: 'Conn. Gen. Stat. § 46b-215a',
      },
      {
        stateCode: 'FL',
        stateName: 'Florida',
        version: '2024',
        effectiveDate: '2024-01-01',
        model: 'income_shares',
        minimumIncome: 650,
        maximumIncome: 10000,
        lowIncomeThreshold: 650,
        selfSupportReserve: 650,
        parentingTimeThreshold: 73,
        parentingTimeFormula: 'Substantial time-sharing adjustment at 73+ overnights (20%)',
        healthInsuranceTreatment: 'add_on',
        childCareTreatment: 'add_on',
        emancipationAge: 18,
        collegeSupportAvailable: false,
        recognizedDeviations: ['Extraordinary medical', 'Independent income of child', 'Seasonal employment', 'Payment for other children'],
        guidelinesUrl: 'https://www.flcourts.org/Resources-Services/Family-Courts/Family-Law-Self-Help-Information/Child-Support',
        calculatorUrl: 'https://www.flcourts.org/content/download/683088/file/child-support-guidelines-worksheet.pdf',
        statuteCitation: 'Fla. Stat. § 61.30',
      },
      {
        stateCode: 'GA',
        stateName: 'Georgia',
        version: '2024',
        effectiveDate: '2024-01-01',
        model: 'income_shares',
        minimumIncome: 0,
        maximumIncome: 30000,
        lowIncomeThreshold: 1850,
        selfSupportReserve: 1850,
        parentingTimeThreshold: 0,
        healthInsuranceTreatment: 'add_on',
        childCareTreatment: 'add_on',
        emancipationAge: 18,
        collegeSupportAvailable: false,
        recognizedDeviations: ['Special needs', 'Life insurance', 'Extraordinary expenses', 'Parenting time'],
        guidelinesUrl: 'https://www.georgiacourts.gov/child-support-guidelines',
        calculatorUrl: 'https://csconline.dhs.ga.gov/calculator/',
        statuteCitation: 'O.C.G.A. § 19-6-15',
      },
      {
        stateCode: 'HI',
        stateName: 'Hawaii',
        version: '2024',
        effectiveDate: '2024-01-01',
        model: 'income_shares',
        minimumIncome: 0,
        maximumIncome: 14000,
        lowIncomeThreshold: 1200,
        selfSupportReserve: 1200,
        parentingTimeThreshold: 0,
        healthInsuranceTreatment: 'add_on',
        childCareTreatment: 'add_on',
        emancipationAge: 18,
        collegeSupportAvailable: true,
        recognizedDeviations: ['Extraordinary medical', 'Educational expenses', 'Travel for visitation', 'Special needs'],
        guidelinesUrl: 'https://www.courts.state.hi.us/self-help/child_support/child_support_guidelines',
        calculatorUrl: 'https://csea.hawaii.gov/',
        statuteCitation: 'HRS § 576D-7',
      },
      {
        stateCode: 'ID',
        stateName: 'Idaho',
        version: '2024',
        effectiveDate: '2024-01-01',
        model: 'income_shares',
        minimumIncome: 0,
        maximumIncome: 24000,
        lowIncomeThreshold: 1200,
        selfSupportReserve: 1200,
        parentingTimeThreshold: 0,
        healthInsuranceTreatment: 'add_on',
        childCareTreatment: 'add_on',
        emancipationAge: 18,
        collegeSupportAvailable: false,
        recognizedDeviations: ['Tax benefits', 'Travel expenses', 'Extraordinary expenses', 'Other dependents'],
        guidelinesUrl: 'https://isc.idaho.gov/irflp/rules',
        calculatorUrl: 'https://healthandwelfare.idaho.gov/services-programs/child-support',
        statuteCitation: 'Idaho Rule of Civil Procedure 6(c)(6)',
      },
      {
        stateCode: 'IL',
        stateName: 'Illinois',
        version: '2024',
        effectiveDate: '2024-01-01',
        model: 'income_shares',
        minimumIncome: 0,
        maximumIncome: 30000,
        lowIncomeThreshold: 1591,
        selfSupportReserve: 1591,
        parentingTimeThreshold: 146,
        parentingTimeFormula: 'Shared parenting adjustment for 146+ overnights (40%)',
        healthInsuranceTreatment: 'add_on',
        childCareTreatment: 'add_on',
        emancipationAge: 18,
        collegeSupportAvailable: true,
        recognizedDeviations: ['Financial resources of both parents', 'Standard of living of child', 'Physical and emotional condition of child', 'Educational needs'],
        guidelinesUrl: 'https://www.illinoiscourts.gov/forms/approved-forms/forms-approved-forms-702-family/',
        calculatorUrl: 'https://www.illinois.gov/hfs/ChildSupport/parents/Pages/estimator.aspx',
        statuteCitation: '750 ILCS 5/505',
      },
      {
        stateCode: 'IN',
        stateName: 'Indiana',
        version: '2024',
        effectiveDate: '2024-01-01',
        model: 'income_shares',
        minimumIncome: 0,
        maximumIncome: 30000,
        lowIncomeThreshold: 1300,
        selfSupportReserve: 1300,
        parentingTimeThreshold: 0,
        healthInsuranceTreatment: 'add_on',
        childCareTreatment: 'add_on',
        emancipationAge: 19,
        collegeSupportAvailable: true,
        recognizedDeviations: ['Extraordinary healthcare', 'Extraordinary education', 'Assets', 'Lifestyle'],
        guidelinesUrl: 'https://www.in.gov/courts/rules/child-support/',
        calculatorUrl: 'https://www.in.gov/dcs/4282.htm',
        statuteCitation: 'Indiana Child Support Rules and Guidelines',
      },
      {
        stateCode: 'IA',
        stateName: 'Iowa',
        version: '2024',
        effectiveDate: '2024-01-01',
        model: 'income_shares',
        minimumIncome: 0,
        maximumIncome: 20000,
        lowIncomeThreshold: 1200,
        selfSupportReserve: 1200,
        parentingTimeThreshold: 127,
        parentingTimeFormula: 'Shared physical care adjustment at 127+ overnights',
        healthInsuranceTreatment: 'add_on',
        childCareTreatment: 'add_on',
        emancipationAge: 19,
        collegeSupportAvailable: true,
        recognizedDeviations: ['Extraordinary medical', 'Extraordinary education', 'Other children', 'Tax consequences'],
        guidelinesUrl: 'https://www.iowacourts.gov/for-the-public/court-rules/chapter-9-child-support-guidelines',
        calculatorUrl: 'https://www.iowacourts.gov/for-the-public/representing-yourself/child-support/',
        statuteCitation: 'Iowa Court Rules 9.1-9.27',
      },
      {
        stateCode: 'KS',
        stateName: 'Kansas',
        version: '2024',
        effectiveDate: '2024-01-01',
        model: 'income_shares',
        minimumIncome: 0,
        maximumIncome: 15000,
        lowIncomeThreshold: 1341,
        selfSupportReserve: 1341,
        parentingTimeThreshold: 0,
        healthInsuranceTreatment: 'add_on',
        childCareTreatment: 'add_on',
        emancipationAge: 18,
        collegeSupportAvailable: true,
        recognizedDeviations: ['Special needs', 'Income imputation', 'Multiple families', 'Parenting time'],
        guidelinesUrl: 'https://www.kscourts.org/KSCourts/media/KsCourts/Rules/Appendix_II_Child_Support_Guidelines.pdf',
        calculatorUrl: 'https://www.kscourts.org/about-the-courts/court-administration/child-support',
        statuteCitation: 'Kansas Administrative Regulation 2016 Child Support Guidelines',
      },
      {
        stateCode: 'KY',
        stateName: 'Kentucky',
        version: '2024',
        effectiveDate: '2024-01-01',
        model: 'income_shares',
        minimumIncome: 0,
        maximumIncome: 15000,
        lowIncomeThreshold: 1191,
        selfSupportReserve: 1191,
        parentingTimeThreshold: 0,
        healthInsuranceTreatment: 'add_on',
        childCareTreatment: 'add_on',
        emancipationAge: 18,
        collegeSupportAvailable: false,
        recognizedDeviations: ['Extraordinary expenses', 'Health insurance', 'Child care', 'Other dependents'],
        guidelinesUrl: 'https://www.kycourts.gov/Legal/Pages/Child-Support.aspx',
        calculatorUrl: 'https://prd.webapps.chfs.ky.gov/kycse_calculator/calculator.aspx',
        statuteCitation: 'KRS 403.212',
      },
      {
        stateCode: 'LA',
        stateName: 'Louisiana',
        version: '2024',
        effectiveDate: '2024-01-01',
        model: 'income_shares',
        minimumIncome: 0,
        maximumIncome: 40000,
        lowIncomeThreshold: 1185,
        selfSupportReserve: 1185,
        parentingTimeThreshold: 0,
        healthInsuranceTreatment: 'add_on',
        childCareTreatment: 'add_on',
        emancipationAge: 18,
        collegeSupportAvailable: false,
        recognizedDeviations: ['Extraordinary medical', 'Seasonal work', 'Support of other children', 'Shared custody'],
        guidelinesUrl: 'https://www.louisianasupremecourt.gov/rules/supreme_court_rules.htm',
        calculatorUrl: 'https://www.dss.state.la.us/page/child-support',
        statuteCitation: 'La. R.S. 9:315',
      },
      {
        stateCode: 'ME',
        stateName: 'Maine',
        version: '2024',
        effectiveDate: '2024-01-01',
        model: 'income_shares',
        minimumIncome: 0,
        maximumIncome: 26000,
        lowIncomeThreshold: 1260,
        selfSupportReserve: 1260,
        parentingTimeThreshold: 30,
        parentingTimeFormula: 'Shared physical care adjustment at 30%+ time',
        healthInsuranceTreatment: 'add_on',
        childCareTreatment: 'add_on',
        emancipationAge: 18,
        collegeSupportAvailable: false,
        recognizedDeviations: ['Extraordinary medical', 'Special needs', 'Other children', 'Cost of living'],
        guidelinesUrl: 'https://www.courts.maine.gov/fees_forms/family/child_support.html',
        calculatorUrl: 'https://www.courts.maine.gov/fees_forms/family/child_support_calculator.html',
        statuteCitation: 'Title 19-A M.R.S. § 2006',
      },
      {
        stateCode: 'MD',
        stateName: 'Maryland',
        version: '2024',
        effectiveDate: '2024-01-01',
        model: 'income_shares',
        minimumIncome: 0,
        maximumIncome: 15000,
        lowIncomeThreshold: 1210,
        selfSupportReserve: 1210,
        parentingTimeThreshold: 128,
        parentingTimeFormula: 'Shared physical custody adjustment at 128+ overnights (35%)',
        healthInsuranceTreatment: 'add_on',
        childCareTreatment: 'add_on',
        emancipationAge: 18,
        collegeSupportAvailable: true,
        recognizedDeviations: ['Extraordinary medical', 'Additional expenses', 'Special needs', 'Alimony paid'],
        guidelinesUrl: 'https://www.mdcourts.gov/family/support',
        calculatorUrl: 'https://childsupport.maryland.gov/Pages/Calculator.aspx',
        statuteCitation: 'Md. Family Law Code Ann. § 12-204',
      },
      {
        stateCode: 'MA',
        stateName: 'Massachusetts',
        version: '2024',
        effectiveDate: '2024-01-01',
        model: 'income_shares',
        minimumIncome: 0,
        maximumIncome: 250000,
        lowIncomeThreshold: 1200,
        selfSupportReserve: 1200,
        parentingTimeThreshold: 0,
        parentingTimeFormula: 'Parenting time credit available for extended visitation',
        healthInsuranceTreatment: 'add_on',
        childCareTreatment: 'add_on',
        emancipationAge: 18,
        collegeSupportAvailable: true,
        recognizedDeviations: ['Child care costs', 'Health insurance', 'Educational expenses', 'Parenting time'],
        guidelinesUrl: 'https://www.mass.gov/info-details/child-support-guidelines',
        calculatorUrl: 'https://www.mass.gov/how-to/use-the-child-support-guidelines-worksheet',
        statuteCitation: 'Massachusetts Trial Court Child Support Guidelines',
      },
      {
        stateCode: 'MI',
        stateName: 'Michigan',
        version: '2024',
        effectiveDate: '2024-01-01',
        model: 'income_shares',
        minimumIncome: 0,
        maximumIncome: 25000,
        lowIncomeThreshold: 1370,
        selfSupportReserve: 1370,
        parentingTimeThreshold: 0,
        parentingTimeFormula: 'Overnights factor into calculation',
        healthInsuranceTreatment: 'add_on',
        childCareTreatment: 'add_on',
        emancipationAge: 18,
        collegeSupportAvailable: false,
        recognizedDeviations: ['Health insurance', 'Child care', 'Education', 'Special circumstances'],
        guidelinesUrl: 'https://courts.michigan.gov/Administration/SCAO/OfficesPrograms/FOC/Pages/ChildSupportFormula.aspx',
        calculatorUrl: 'https://micase.state.mi.us/calculators/childsupportcalculator/',
        statuteCitation: 'MCL 552.519',
      },
      {
        stateCode: 'MN',
        stateName: 'Minnesota',
        version: '2024',
        effectiveDate: '2024-01-01',
        model: 'income_shares',
        minimumIncome: 0,
        maximumIncome: 99999,
        lowIncomeThreshold: 1452,
        selfSupportReserve: 1452,
        parentingTimeThreshold: 45.1,
        parentingTimeFormula: 'Parenting expense adjustment at 45.1%+ time',
        healthInsuranceTreatment: 'add_on',
        childCareTreatment: 'add_on',
        emancipationAge: 18,
        collegeSupportAvailable: false,
        recognizedDeviations: ['Medical support', 'Child care support', 'Parenting expense adjustment', 'Income sources'],
        guidelinesUrl: 'https://www.mncourts.gov/Help-Topics/Child-Support.aspx',
        calculatorUrl: 'https://childsupportcalculator.dhs.state.mn.us/',
        statuteCitation: 'Minn. Stat. § 518A.35',
      },
      {
        stateCode: 'MO',
        stateName: 'Missouri',
        version: '2024',
        effectiveDate: '2024-01-01',
        model: 'income_shares',
        minimumIncome: 0,
        maximumIncome: 15000,
        lowIncomeThreshold: 1100,
        selfSupportReserve: 1100,
        parentingTimeThreshold: 0,
        healthInsuranceTreatment: 'add_on',
        childCareTreatment: 'add_on',
        emancipationAge: 21,
        collegeSupportAvailable: true,
        recognizedDeviations: ['Extraordinary expenses', 'Health insurance', 'Child care', 'Education'],
        guidelinesUrl: 'https://www.courts.mo.gov/page.jsp?id=549',
        calculatorUrl: 'https://www.courts.mo.gov/calc/default.htm',
        statuteCitation: 'Section 452.340 RSMo',
      },
      {
        stateCode: 'MT',
        stateName: 'Montana',
        version: '2024',
        effectiveDate: '2024-01-01',
        model: 'income_shares',
        minimumIncome: 0,
        maximumIncome: 15000,
        lowIncomeThreshold: 1200,
        selfSupportReserve: 1200,
        parentingTimeThreshold: 110,
        parentingTimeFormula: 'Shared parenting adjustment at 110+ overnights',
        healthInsuranceTreatment: 'add_on',
        childCareTreatment: 'add_on',
        emancipationAge: 18,
        collegeSupportAvailable: false,
        recognizedDeviations: ['Long distance visitation', 'Unusual needs', 'Other dependents', 'Financial resources'],
        guidelinesUrl: 'https://courts.mt.gov/forms/child_support',
        calculatorUrl: 'https://dphhs.mt.gov/csed/parenthelp/howitscalculated',
        statuteCitation: 'Admin. R. Mont. 37.62.101',
      },
      {
        stateCode: 'NE',
        stateName: 'Nebraska',
        version: '2024',
        effectiveDate: '2024-01-01',
        model: 'income_shares',
        minimumIncome: 0,
        maximumIncome: 15000,
        lowIncomeThreshold: 1100,
        selfSupportReserve: 1100,
        parentingTimeThreshold: 142,
        parentingTimeFormula: 'Joint physical custody adjustment at 142+ overnights',
        healthInsuranceTreatment: 'add_on',
        childCareTreatment: 'add_on',
        emancipationAge: 19,
        collegeSupportAvailable: false,
        recognizedDeviations: ['Transportation costs', 'Special needs', 'Extraordinary expenses', 'Variances'],
        guidelinesUrl: 'https://supremecourt.nebraska.gov/child-support-guidelines',
        calculatorUrl: 'https://cse.nebraska.gov/online_services/calculators',
        statuteCitation: 'Neb. Rev. Stat. § 42-364.16',
      },
      {
        stateCode: 'NJ',
        stateName: 'New Jersey',
        version: '2024',
        effectiveDate: '2024-01-01',
        model: 'income_shares',
        minimumIncome: 0,
        maximumIncome: 18720,
        lowIncomeThreshold: 1560,
        selfSupportReserve: 1560,
        parentingTimeThreshold: 28,
        parentingTimeFormula: 'Shared parenting adjustment at 28%+ overnights',
        healthInsuranceTreatment: 'add_on',
        childCareTreatment: 'add_on',
        emancipationAge: 19,
        collegeSupportAvailable: true,
        recognizedDeviations: ['Extraordinary expenses', 'College education', 'Private school', 'Special needs'],
        guidelinesUrl: 'https://www.njcourts.gov/family/childsupport',
        calculatorUrl: 'https://www.njchildsupport.org/Resources/Calculators.aspx',
        statuteCitation: 'N.J. Court Rule 5:6A',
      },
      {
        stateCode: 'NM',
        stateName: 'New Mexico',
        version: '2024',
        effectiveDate: '2024-01-01',
        model: 'income_shares',
        minimumIncome: 0,
        maximumIncome: 25000,
        lowIncomeThreshold: 1200,
        selfSupportReserve: 1200,
        parentingTimeThreshold: 0,
        healthInsuranceTreatment: 'add_on',
        childCareTreatment: 'add_on',
        emancipationAge: 18,
        collegeSupportAvailable: false,
        recognizedDeviations: ['Work-related child care', 'Health insurance', 'Extraordinary expenses', 'Other children'],
        guidelinesUrl: 'https://www.nmcourts.gov/forms-and-fees/forms.aspx',
        calculatorUrl: 'https://childsupport.nmcourts.gov/',
        statuteCitation: 'NMSA 1978 § 40-4-11.1',
      },
      {
        stateCode: 'NY',
        stateName: 'New York',
        version: '2024',
        effectiveDate: '2024-01-01',
        model: 'income_shares',
        minimumIncome: 0,
        maximumIncome: 163000,
        lowIncomeThreshold: 1479,
        selfSupportReserve: 1479,
        parentingTimeThreshold: 0,
        parentingTimeFormula: 'Percentage of combined parental income',
        percentageRates: [
          { numberOfChildren: 1, percentage: 17 },
          { numberOfChildren: 2, percentage: 25 },
          { numberOfChildren: 3, percentage: 29 },
          { numberOfChildren: 4, percentage: 31 },
          { numberOfChildren: 5, percentage: 35 },
        ],
        healthInsuranceTreatment: 'add_on',
        childCareTreatment: 'add_on',
        emancipationAge: 21,
        collegeSupportAvailable: true,
        recognizedDeviations: ['Financial resources of parents and child', 'Physical and emotional health of child', 'Standard of living child would have enjoyed', 'Tax consequences'],
        guidelinesUrl: 'https://www.nycourts.gov/courthelp/Family/childSupport.shtml',
        calculatorUrl: 'https://www.childsupport.ny.gov/dcse/child_support_guidelines.html',
        statuteCitation: 'NY Dom. Rel. Law § 240',
      },
      {
        stateCode: 'NC',
        stateName: 'North Carolina',
        version: '2024',
        effectiveDate: '2024-01-01',
        model: 'income_shares',
        minimumIncome: 0,
        maximumIncome: 25000,
        lowIncomeThreshold: 1197,
        selfSupportReserve: 1197,
        parentingTimeThreshold: 123,
        parentingTimeFormula: 'Shared custody adjustment at 123+ overnights',
        healthInsuranceTreatment: 'add_on',
        childCareTreatment: 'add_on',
        emancipationAge: 18,
        collegeSupportAvailable: false,
        recognizedDeviations: ['Health insurance', 'Child care', 'Extraordinary expenses', 'Educational expenses'],
        guidelinesUrl: 'https://www.nccourts.gov/help-topics/family-and-children/child-support',
        calculatorUrl: 'https://www.nccourts.gov/documents/forms/child-support-worksheet-a-primary-custody',
        statuteCitation: 'N.C. Gen. Stat. § 50-13.4',
      },
      {
        stateCode: 'ND',
        stateName: 'North Dakota',
        version: '2024',
        effectiveDate: '2024-01-01',
        model: 'income_shares',
        minimumIncome: 0,
        maximumIncome: 15000,
        lowIncomeThreshold: 1100,
        selfSupportReserve: 1100,
        parentingTimeThreshold: 0,
        healthInsuranceTreatment: 'add_on',
        childCareTreatment: 'add_on',
        emancipationAge: 18,
        collegeSupportAvailable: false,
        recognizedDeviations: ['Child care costs', 'Health insurance', 'Extended visitation', 'Special needs'],
        guidelinesUrl: 'https://www.ndcourts.gov/child-support',
        calculatorUrl: 'https://childsupport.nd.gov/calculators-forms/guideline-calculator/',
        statuteCitation: 'N.D. Admin. Code 75-02-04.1',
      },
      {
        stateCode: 'OH',
        stateName: 'Ohio',
        version: '2024',
        effectiveDate: '2024-01-01',
        model: 'income_shares',
        minimumIncome: 0,
        maximumIncome: 30500,
        lowIncomeThreshold: 1160,
        selfSupportReserve: 1160,
        parentingTimeThreshold: 90,
        parentingTimeFormula: 'Shared parenting adjustment at 90+ overnights (25%)',
        healthInsuranceTreatment: 'add_on',
        childCareTreatment: 'add_on',
        emancipationAge: 18,
        collegeSupportAvailable: false,
        recognizedDeviations: ['Extended parenting time', 'Extraordinary expenses', 'Other children', 'Special needs'],
        guidelinesUrl: 'https://www.supremecourt.ohio.gov/JCS/domesticViolence/publications/ChildSupport.pdf',
        calculatorUrl: 'https://jfs.ohio.gov/Ocs/pdf/BasicChildSupportSchedule.stm',
        statuteCitation: 'Ohio Rev. Code Ann. § 3119.021',
      },
      {
        stateCode: 'OK',
        stateName: 'Oklahoma',
        version: '2024',
        effectiveDate: '2024-01-01',
        model: 'income_shares',
        minimumIncome: 0,
        maximumIncome: 15000,
        lowIncomeThreshold: 1100,
        selfSupportReserve: 1100,
        parentingTimeThreshold: 121,
        parentingTimeFormula: 'Shared parenting adjustment at 121+ overnights',
        healthInsuranceTreatment: 'add_on',
        childCareTreatment: 'add_on',
        emancipationAge: 18,
        collegeSupportAvailable: false,
        recognizedDeviations: ['Medical insurance', 'Child care', 'Extraordinary expenses', 'Other children'],
        guidelinesUrl: 'https://www.oscn.net/applications/oscn/index.asp?ftdb=STOKST43&level=1',
        calculatorUrl: 'https://www.okdhs.org/services/ocss/Pages/Calculator.aspx',
        statuteCitation: '43 Okla. Stat. § 118',
      },
      {
        stateCode: 'OR',
        stateName: 'Oregon',
        version: '2024',
        effectiveDate: '2024-01-01',
        model: 'income_shares',
        minimumIncome: 0,
        maximumIncome: 30000,
        lowIncomeThreshold: 1210,
        selfSupportReserve: 1210,
        parentingTimeThreshold: 25,
        parentingTimeFormula: 'Parenting time credit at 25%+ overnights',
        healthInsuranceTreatment: 'add_on',
        childCareTreatment: 'add_on',
        emancipationAge: 18,
        collegeSupportAvailable: false,
        recognizedDeviations: ['Child care', 'Health insurance', 'Special needs', 'Transportation'],
        guidelinesUrl: 'https://www.courts.oregon.gov/programs/family/child-support/Pages/default.aspx',
        calculatorUrl: 'https://justice.oregon.gov/CSCU/Index',
        statuteCitation: 'ORS 25.275',
      },
      {
        stateCode: 'PA',
        stateName: 'Pennsylvania',
        version: '2024',
        effectiveDate: '2024-01-01',
        model: 'income_shares',
        minimumIncome: 0,
        maximumIncome: 30000,
        lowIncomeThreshold: 1100,
        selfSupportReserve: 1100,
        parentingTimeThreshold: 40,
        parentingTimeFormula: 'Shared custody adjustment at 40%+ time',
        healthInsuranceTreatment: 'add_on',
        childCareTreatment: 'add_on',
        emancipationAge: 18,
        collegeSupportAvailable: true,
        recognizedDeviations: ['Health insurance', 'Child care', 'Extraordinary expenses', 'Multiple families'],
        guidelinesUrl: 'https://www.pacourts.us/learn/representing-yourself/child-support',
        calculatorUrl: 'https://www.humanservices.state.pa.us/CSWS/CSWS_controller.aspx?id=Calculator',
        statuteCitation: '23 Pa.C.S. § 4322',
      },
      {
        stateCode: 'RI',
        stateName: 'Rhode Island',
        version: '2024',
        effectiveDate: '2024-01-01',
        model: 'income_shares',
        minimumIncome: 0,
        maximumIncome: 15000,
        lowIncomeThreshold: 1210,
        selfSupportReserve: 1210,
        parentingTimeThreshold: 0,
        healthInsuranceTreatment: 'add_on',
        childCareTreatment: 'add_on',
        emancipationAge: 18,
        collegeSupportAvailable: true,
        recognizedDeviations: ['Extraordinary medical', 'Child care', 'Educational expenses', 'Split custody'],
        guidelinesUrl: 'https://www.courts.ri.gov/Courts/FamilyCourt/Pages/ChildSupport.aspx',
        calculatorUrl: 'https://cse.ri.gov/child-support-guidelines',
        statuteCitation: 'R.I. Gen. Laws § 15-5-16.2',
      },
      {
        stateCode: 'SC',
        stateName: 'South Carolina',
        version: '2024',
        effectiveDate: '2024-01-01',
        model: 'income_shares',
        minimumIncome: 0,
        maximumIncome: 30000,
        lowIncomeThreshold: 1006,
        selfSupportReserve: 1006,
        parentingTimeThreshold: 109,
        parentingTimeFormula: 'Shared custody adjustment at 109+ overnights',
        healthInsuranceTreatment: 'add_on',
        childCareTreatment: 'add_on',
        emancipationAge: 18,
        collegeSupportAvailable: true,
        recognizedDeviations: ['Extraordinary medical', 'Educational expenses', 'Special needs', 'Equitable distribution'],
        guidelinesUrl: 'https://www.sccourts.org/forms/childsupportguide.cfm',
        calculatorUrl: 'https://dss.sc.gov/child-support/how-support-is-calculated/',
        statuteCitation: 'S.C. Code Ann. Reg. 114-4720',
      },
      {
        stateCode: 'SD',
        stateName: 'South Dakota',
        version: '2024',
        effectiveDate: '2024-01-01',
        model: 'income_shares',
        minimumIncome: 0,
        maximumIncome: 10000,
        lowIncomeThreshold: 1100,
        selfSupportReserve: 1100,
        parentingTimeThreshold: 0,
        healthInsuranceTreatment: 'add_on',
        childCareTreatment: 'add_on',
        emancipationAge: 18,
        collegeSupportAvailable: false,
        recognizedDeviations: ['Medical support', 'Child care', 'Other dependents', 'Special circumstances'],
        guidelinesUrl: 'https://ujs.sd.gov/Family/Child_Support.aspx',
        calculatorUrl: 'https://ujs.sd.gov/media/family/SupportObligationSchedule.pdf',
        statuteCitation: 'SDCL § 25-7-6.2',
      },
      {
        stateCode: 'TN',
        stateName: 'Tennessee',
        version: '2024',
        effectiveDate: '2024-01-01',
        model: 'income_shares',
        minimumIncome: 0,
        maximumIncome: 15000,
        lowIncomeThreshold: 1207,
        selfSupportReserve: 1207,
        parentingTimeThreshold: 92,
        parentingTimeFormula: 'Parenting time adjustment at 92+ days (25%)',
        healthInsuranceTreatment: 'add_on',
        childCareTreatment: 'add_on',
        emancipationAge: 18,
        collegeSupportAvailable: false,
        recognizedDeviations: ['Health insurance', 'Extraordinary expenses', 'Long distance visitation', 'Other children'],
        guidelinesUrl: 'https://www.tncourts.gov/programs/child-support-services/tennessee-child-support-guidelines',
        calculatorUrl: 'https://www.tn.gov/humanservices/for-families/child-support-services/child-support-services-calculator.html',
        statuteCitation: 'Tenn. Comp. R. & Regs. 1240-2-4',
      },
      {
        stateCode: 'UT',
        stateName: 'Utah',
        version: '2024',
        effectiveDate: '2024-01-01',
        model: 'income_shares',
        minimumIncome: 0,
        maximumIncome: 30000,
        lowIncomeThreshold: 1100,
        selfSupportReserve: 1100,
        parentingTimeThreshold: 111,
        parentingTimeFormula: 'Joint physical custody adjustment at 111+ overnights',
        healthInsuranceTreatment: 'add_on',
        childCareTreatment: 'add_on',
        emancipationAge: 18,
        collegeSupportAvailable: false,
        recognizedDeviations: ['Medical insurance', 'Child care', 'Transportation', 'Special needs'],
        guidelinesUrl: 'https://www.utcourts.gov/howto/family/child_support/',
        calculatorUrl: 'https://www.utcourts.gov/ocs/index.html',
        statuteCitation: 'Utah Code Ann. § 78B-12-301',
      },
      {
        stateCode: 'VT',
        stateName: 'Vermont',
        version: '2024',
        effectiveDate: '2024-01-01',
        model: 'income_shares',
        minimumIncome: 0,
        maximumIncome: 18000,
        lowIncomeThreshold: 1210,
        selfSupportReserve: 1210,
        parentingTimeThreshold: 30,
        parentingTimeFormula: 'Shared custody adjustment at 30%+ parenting time',
        healthInsuranceTreatment: 'add_on',
        childCareTreatment: 'add_on',
        emancipationAge: 18,
        collegeSupportAvailable: true,
        recognizedDeviations: ['Health insurance', 'Child care', 'Extraordinary expenses', 'Travel expenses'],
        guidelinesUrl: 'https://dcf.vermont.gov/ocs/parents/guidelines',
        calculatorUrl: 'https://dcf.vermont.gov/ocs/parents/calculator',
        statuteCitation: '15 V.S.A. § 659',
      },
      {
        stateCode: 'VA',
        stateName: 'Virginia',
        version: '2024',
        effectiveDate: '2024-01-01',
        model: 'income_shares',
        minimumIncome: 0,
        maximumIncome: 35000,
        lowIncomeThreshold: 1200,
        selfSupportReserve: 1200,
        parentingTimeThreshold: 90,
        parentingTimeFormula: 'Shared custody adjustment at 90+ days',
        healthInsuranceTreatment: 'add_on',
        childCareTreatment: 'add_on',
        emancipationAge: 18,
        collegeSupportAvailable: true,
        recognizedDeviations: ['Travel costs', 'Extraordinary expenses', 'Independent living child', 'Educational expenses'],
        guidelinesUrl: 'https://www.vacourts.gov/courts/circuit/resources/child_support_guidelines.pdf',
        calculatorUrl: 'https://www.dss.virginia.gov/family/dcse/child_support_calculator.cgi',
        statuteCitation: 'Va. Code Ann. § 20-108.2',
      },
      {
        stateCode: 'WA',
        stateName: 'Washington',
        version: '2024',
        effectiveDate: '2024-01-01',
        model: 'income_shares',
        minimumIncome: 0,
        maximumIncome: 14000,
        lowIncomeThreshold: 1477,
        selfSupportReserve: 1477,
        parentingTimeThreshold: 0,
        parentingTimeFormula: 'Residential time credit available',
        healthInsuranceTreatment: 'add_on',
        childCareTreatment: 'add_on',
        emancipationAge: 18,
        collegeSupportAvailable: true,
        recognizedDeviations: ['Day care', 'Health care', 'Special needs', 'Transportation'],
        guidelinesUrl: 'https://www.courts.wa.gov/forms/?fa=forms.contribute&formID=16',
        calculatorUrl: 'https://www.dshs.wa.gov/esa/division-child-support/how-child-support-calculated',
        statuteCitation: 'RCW 26.19.020',
      },
      {
        stateCode: 'WV',
        stateName: 'West Virginia',
        version: '2024',
        effectiveDate: '2024-01-01',
        model: 'income_shares',
        minimumIncome: 0,
        maximumIncome: 15500,
        lowIncomeThreshold: 1155,
        selfSupportReserve: 1155,
        parentingTimeThreshold: 127,
        parentingTimeFormula: 'Extended visitation adjustment at 127+ overnights',
        healthInsuranceTreatment: 'add_on',
        childCareTreatment: 'add_on',
        emancipationAge: 18,
        collegeSupportAvailable: false,
        recognizedDeviations: ['Health insurance', 'Child care', 'Extraordinary medical', 'Extended visitation'],
        guidelinesUrl: 'https://dhhr.wv.gov/bcse/Pages/Guidelines.aspx',
        calculatorUrl: 'https://dhhr.wv.gov/bcse/calculator/Pages/default.aspx',
        statuteCitation: 'W. Va. Code § 48-13-101',
      },
      {
        stateCode: 'WI',
        stateName: 'Wisconsin',
        version: '2024',
        effectiveDate: '2024-01-01',
        model: 'income_shares',
        minimumIncome: 0,
        maximumIncome: 20000,
        lowIncomeThreshold: 1550,
        selfSupportReserve: 1550,
        parentingTimeThreshold: 92,
        parentingTimeFormula: 'Shared custody adjustment at 92+ overnights (25%)',
        healthInsuranceTreatment: 'add_on',
        childCareTreatment: 'add_on',
        emancipationAge: 18,
        collegeSupportAvailable: false,
        recognizedDeviations: ['Variable income', 'High income', 'Serial family', 'Shared placement'],
        guidelinesUrl: 'https://dcf.wisconsin.gov/cs/order/guidelines',
        calculatorUrl: 'https://dcf.wisconsin.gov/cs/tools',
        statuteCitation: 'Wis. Admin. Code DCF § 150',
      },
      {
        stateCode: 'WY',
        stateName: 'Wyoming',
        version: '2024',
        effectiveDate: '2024-01-01',
        model: 'income_shares',
        minimumIncome: 0,
        maximumIncome: 16500,
        lowIncomeThreshold: 1100,
        selfSupportReserve: 1100,
        parentingTimeThreshold: 0,
        healthInsuranceTreatment: 'add_on',
        childCareTreatment: 'add_on',
        emancipationAge: 18,
        collegeSupportAvailable: false,
        recognizedDeviations: ['Health insurance', 'Child care', 'Extraordinary expenses', 'Other children'],
        guidelinesUrl: 'https://www.courts.state.wy.us/legal-assistance/family-law-forms/',
        calculatorUrl: 'https://childsupport.dfs.wyo.gov/',
        statuteCitation: 'Wyo. Stat. Ann. § 20-2-304',
      },

      // PERCENTAGE OF INCOME MODEL STATES
      {
        stateCode: 'TX',
        stateName: 'Texas',
        version: '2024',
        effectiveDate: '2024-01-01',
        model: 'percentage_of_income',
        maximumIncome: 9200,
        lowIncomeThreshold: 1013,
        selfSupportReserve: 1013,
        parentingTimeThreshold: 0,
        parentingTimeFormula: 'Percentage applied to net resources',
        percentageRates: [
          { numberOfChildren: 1, percentage: 20 },
          { numberOfChildren: 2, percentage: 25 },
          { numberOfChildren: 3, percentage: 30 },
          { numberOfChildren: 4, percentage: 35 },
          { numberOfChildren: 5, percentage: 40 },
          { numberOfChildren: 6, percentage: 40 },
        ],
        healthInsuranceTreatment: 'add_on',
        childCareTreatment: 'add_on',
        emancipationAge: 18,
        collegeSupportAvailable: false,
        recognizedDeviations: ['Special or extraordinary needs', 'Shared custody arrangement', 'Educational expenses', 'Travel costs for possession'],
        guidelinesUrl: 'https://www.texasattorneygeneral.gov/child-support',
        calculatorUrl: 'https://csapps.oag.texas.gov/calculator/estimator',
        statuteCitation: 'Tex. Fam. Code Ann. § 154.125',
      },
      {
        stateCode: 'MS',
        stateName: 'Mississippi',
        version: '2024',
        effectiveDate: '2024-01-01',
        model: 'percentage_of_income',
        minimumIncome: 0,
        maximumIncome: 50000,
        lowIncomeThreshold: 1000,
        selfSupportReserve: 1000,
        parentingTimeThreshold: 0,
        percentageRates: [
          { numberOfChildren: 1, percentage: 14 },
          { numberOfChildren: 2, percentage: 20 },
          { numberOfChildren: 3, percentage: 22 },
          { numberOfChildren: 4, percentage: 24 },
          { numberOfChildren: 5, percentage: 26 },
        ],
        healthInsuranceTreatment: 'add_on',
        childCareTreatment: 'add_on',
        emancipationAge: 21,
        collegeSupportAvailable: false,
        recognizedDeviations: ['Extraordinary medical', 'Seasonal employment', 'Other children', 'Special needs'],
        guidelinesUrl: 'https://www.mdhs.ms.gov/child-support-enforcement/',
        calculatorUrl: 'https://www.mdhs.ms.gov/child-support-enforcement/',
        statuteCitation: 'Miss. Code Ann. § 43-19-101',
      },
      {
        stateCode: 'NV',
        stateName: 'Nevada',
        version: '2024',
        effectiveDate: '2024-01-01',
        model: 'percentage_of_income',
        minimumIncome: 0,
        maximumIncome: 18000,
        lowIncomeThreshold: 1100,
        selfSupportReserve: 1100,
        parentingTimeThreshold: 0,
        percentageRates: [
          { numberOfChildren: 1, percentage: 18 },
          { numberOfChildren: 2, percentage: 25 },
          { numberOfChildren: 3, percentage: 29 },
          { numberOfChildren: 4, percentage: 31 },
        ],
        healthInsuranceTreatment: 'add_on',
        childCareTreatment: 'add_on',
        emancipationAge: 18,
        collegeSupportAvailable: false,
        recognizedDeviations: ['Cost of health insurance', 'Child care', 'Special education needs', 'Travel expenses'],
        guidelinesUrl: 'https://dwss.nv.gov/CSEP/Home/',
        calculatorUrl: 'https://nvchildsupport.nv.gov/Calculator/',
        statuteCitation: 'NRS 125B.070',
      },
      {
        stateCode: 'AK',
        stateName: 'Alaska',
        version: '2024',
        effectiveDate: '2024-01-01',
        model: 'percentage_of_income',
        minimumIncome: 0,
        maximumIncome: 126000,
        lowIncomeThreshold: 1200,
        selfSupportReserve: 1200,
        parentingTimeThreshold: 110,
        parentingTimeFormula: 'Shared custody formula at 110+ overnights (30%)',
        percentageRates: [
          { numberOfChildren: 1, percentage: 20 },
          { numberOfChildren: 2, percentage: 27 },
          { numberOfChildren: 3, percentage: 33 },
          { numberOfChildren: 4, percentage: 36 },
          { numberOfChildren: 5, percentage: 39 },
        ],
        healthInsuranceTreatment: 'add_on',
        childCareTreatment: 'add_on',
        emancipationAge: 18,
        collegeSupportAvailable: false,
        recognizedDeviations: ['Extraordinary medical', 'Special needs', 'Distance travel', 'Other children'],
        guidelinesUrl: 'https://public.courts.alaska.gov/web/rules/docs/civ.pdf',
        calculatorUrl: 'https://webapp.prior.dofg.alaska.gov/cssd/CSSDCalc/Default.aspx',
        statuteCitation: 'Alaska R. Civ. P. 90.3',
      },

      // MELSON FORMULA STATES (3 states)
      {
        stateCode: 'DE',
        stateName: 'Delaware',
        version: '2024',
        effectiveDate: '2024-01-01',
        model: 'melson_formula',
        minimumIncome: 0,
        maximumIncome: 999999,
        lowIncomeThreshold: 1200,
        selfSupportReserve: 1200,
        povertyLevelReference: 1452,
        parentingTimeThreshold: 0,
        parentingTimeFormula: 'Time-sharing adjustment based on overnights',
        healthInsuranceTreatment: 'included',
        childCareTreatment: 'included',
        emancipationAge: 18,
        collegeSupportAvailable: true,
        recognizedDeviations: ['Extraordinary medical', 'Private school', 'Special needs', 'Other household members'],
        guidelinesUrl: 'https://courts.delaware.gov/family/guidelines.aspx',
        calculatorUrl: 'https://courts.delaware.gov/family/calculator.aspx',
        statuteCitation: 'Family Court Civil Rule 52(c)',
      },
      {
        stateCode: 'HI',
        stateName: 'Hawaii',
        version: '2024',
        effectiveDate: '2024-01-01',
        model: 'melson_formula',
        minimumIncome: 0,
        maximumIncome: 14000,
        lowIncomeThreshold: 1200,
        selfSupportReserve: 1200,
        povertyLevelReference: 1430,
        parentingTimeThreshold: 0,
        healthInsuranceTreatment: 'add_on',
        childCareTreatment: 'add_on',
        emancipationAge: 18,
        collegeSupportAvailable: true,
        recognizedDeviations: ['Extraordinary medical', 'Educational expenses', 'Travel for visitation', 'Special needs'],
        guidelinesUrl: 'https://www.courts.state.hi.us/self-help/child_support/child_support_guidelines',
        calculatorUrl: 'https://csea.hawaii.gov/',
        statuteCitation: 'HRS § 576D-7',
      },
      {
        stateCode: 'MT',
        stateName: 'Montana',
        version: '2024-Melson',
        effectiveDate: '2024-01-01',
        model: 'melson_formula',
        minimumIncome: 0,
        maximumIncome: 15000,
        lowIncomeThreshold: 1200,
        selfSupportReserve: 1200,
        povertyLevelReference: 1310,
        parentingTimeThreshold: 110,
        parentingTimeFormula: 'Shared parenting adjustment at 110+ overnights',
        healthInsuranceTreatment: 'add_on',
        childCareTreatment: 'add_on',
        emancipationAge: 18,
        collegeSupportAvailable: false,
        recognizedDeviations: ['Long distance visitation', 'Unusual needs', 'Other dependents', 'Financial resources'],
        guidelinesUrl: 'https://courts.mt.gov/forms/child_support',
        calculatorUrl: 'https://dphhs.mt.gov/csed/parenthelp/howitscalculated',
        statuteCitation: 'Admin. R. Mont. 37.62.101',
      },
      {
        stateCode: 'NH',
        stateName: 'New Hampshire',
        version: '2024',
        effectiveDate: '2024-01-01',
        model: 'income_shares',
        minimumIncome: 0,
        maximumIncome: 25000,
        lowIncomeThreshold: 1100,
        selfSupportReserve: 1100,
        parentingTimeThreshold: 0,
        healthInsuranceTreatment: 'add_on',
        childCareTreatment: 'add_on',
        emancipationAge: 18,
        collegeSupportAvailable: false,
        recognizedDeviations: ['Extraordinary medical', 'Child care', 'Special needs', 'Transportation'],
        guidelinesUrl: 'https://www.courts.state.nh.us/fdpp/child-support.htm',
        calculatorUrl: 'https://www.dhhs.nh.gov/dcss/calculator.htm',
        statuteCitation: 'RSA 458-C:3',
      },
    ];
  }
}

